### ISSUE TITLE
ERROR: xxxxx does not implement rsp format ?

### ISSUE THREAD

**Issue by alanNz** [mesonbuild/meson#8800]
I get this error on two of my builds for xc16 and c2000 targets, I'm not sure why?

"ERROR: ar2000 does no implemnt rsp format, this shouldn't be called"
"ERROR: xc16-ar does no implemnt rsp format, this shouldn't be called"

Both projects had been working on Meson 0.57.1. I have just upgraded to meson 0.58.0 and its the first error I get

I seem to have found this spot in the code, mentioning it's not implemented? Is that the case?
`
If `self.can_linker_accept_rsp()` returns True, then this needs to        
be implemented        
"""        
assert not self.can_linker_accept_rsp(), f'{self.id} linker accepts RSP, but doesn\' provide a supported format, this is a bug'     
raise mesonlib.EnvironmentException(f'{self.id} does no implemnt rsp format, this shouldn\'t be called')

`

**Comment by dcbaker** [comment]
Can you see if #8804 fixes this for you?

**Comment by alanNz** [comment]
yes, 8804 has fixed it for me on both xc16 and c2000. Thank you very much
