### ISSUE TITLE
Meson 1.11 fails to detect Qt5 tools on Windows

### ISSUE THREAD

**Issue by chkurz** [mesonbuild/meson#15705]
**Describe the bug**
With the availability of version 1.11.0, our Windows CI pipeline has started to fail:

```
Detecting Qt5 tools

modules\source\CustomQtWidgets\meson.build:14:36: ERROR: Dependency lookup for qt5 with method 'config-tool' failed: 'NoneType' object has no attribute 'extend'

    This is a Meson bug and should be reported!
```

The offending code block with some context:

```
qt5_mod = import('qt5') #from main meson.build

CustomQtWidgets_moc_headers = files(...)

CustomQtWidgets_processed = qt5_mod.preprocess( # this is line 14
  moc_headers: CustomQtWidgets_moc_headers,
)
```

I've tested this on Linux (Python 3.13.9), where it appears to be working fine.

**To Reproduce**
Unfortunately, I can't devote any resources to this at the moment, as this bug has only shown up in CI under Windows and pinning the version to 1.10.2 has fixed the issue.

**Expected behavior**
Setup should not fail.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Native**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **windows-server-2022-gui:2025.10.1** on CircleCI
* what Python version are you using e.g. 3.8.0 **python v3.13.7**
* what `meson --version` **1.11.0**
* what `ninja --version` if it's a Ninja build

**Comment by bonzini** [comment]
Can you at least try running your CI once with unpinned meson and `MESON_FORCE_BACKTRACE=1` in the environment?

**Comment by chkurz** [comment]
Here's the backtrace:
```
Traceback (most recent call last):
  File "C:\Python313\Lib\site-packages\mesonbuild\dependencies\detect.py", line 120, in find_external_dependency
    d = c()
  File "C:\Python313\Lib\site-packages\mesonbuild\dependencies\base.py", line 705, in __call__
    return self.callable(self.name, env, kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\dependencies\qt.py", line 270, in __init__
    _vers.extend([f'>= {self.qtver}', f'< {int(self.qtver) + 1}'])
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'extend'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python313\Scripts\meson.exe\__main__.py", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Python313\Lib\site-packages\mesonbuild\mesonmain.py", line 313, in main
    return run(sys.argv[1:], launcher)
  File "C:\Python313\Lib\site-packages\mesonbuild\mesonmain.py", line 304, in run
    return CommandLineParser().run(args)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\mesonmain.py", line 195, in run
    return errorhandler(e, command)
  File "C:\Python313\Lib\site-packages\mesonbuild\mesonmain.py", line 34, in errorhandler
    raise e
  File "C:\Python313\Lib\site-packages\mesonbuild\mesonmain.py", line 193, in run
    return options.run_func(options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\msetup.py", line 404, in run
    app.generate()
    ~~~~~~~~~~~~^^
  File "C:\Python313\Lib\site-packages\mesonbuild\msetup.py", line 196, in generate
    return self._generate(env, capture, vslite_ctx)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\msetup.py", line 255, in _generate
    intr.run()
    ~~~~~~~~^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 3119, in run
    super().run()
    ~~~~~~~~~~~^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 179, in run
    self.evaluate_codeblock(self.ast, start=1)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 204, in evaluate_codeblock
    raise e
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 210, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 520, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 601, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2521, in func_subdir
    elif not self._evaluate_subdir(self.environment.get_source_dir(), subdir):
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 711, in _evaluate_subdir
    self._evaluate_codeblock(codeblock, subdir, visitors)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 722, in _evaluate_codeblock
    self.evaluate_codeblock(codeblock)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 204, in evaluate_codeblock
    raise e
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 210, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 520, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 601, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2521, in func_subdir
    elif not self._evaluate_subdir(self.environment.get_source_dir(), subdir):
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 711, in _evaluate_subdir
    self._evaluate_codeblock(codeblock, subdir, visitors)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 722, in _evaluate_codeblock
    self.evaluate_codeblock(codeblock)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 204, in evaluate_codeblock
    raise e
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 210, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 520, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 601, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2521, in func_subdir
    elif not self._evaluate_subdir(self.environment.get_source_dir(), subdir):
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 711, in _evaluate_subdir
    self._evaluate_codeblock(codeblock, subdir, visitors)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 722, in _evaluate_codeblock
    self.evaluate_codeblock(codeblock)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 204, in evaluate_codeblock
    raise e
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 214, in evaluate_statement
    self.assignment(cur)
    ~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 628, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 216, in evaluate_statement
    return self.method_call(cur)
           ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 543, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreter\interpreterobjects.py", line 963, in method_call
    ret = method(state, args, kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 601, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Python313\Lib\site-packages\mesonbuild\modules\_qt.py", line 680, in preprocess
    sources.extend(self._compile_moc_impl(state, moc_kwargs))
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\modules\_qt.py", line 564, in _compile_moc_impl
    self._detect_tools(state, kwargs['method'])
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\modules\_qt.py", line 276, in _detect_tools
    qt = T.cast('QtPkgConfigDependency', find_external_dependency(f'qt{self.qt_version}', state.environment, kwargs))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\mesonbuild\dependencies\detect.py", line 132, in find_external_dependency
    raise MesonBugException(bettermsg) from e
mesonbuild.utils.core.MesonBugException: Dependency lookup for qt5 with method 'config-tool' failed: 'NoneType' object has no attribute 'extend'

    This is a Meson bug and should be reported!
```

**Comment by bonzini** [comment]
Thanks, caused by ab9cffb.
