### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_env'

### ISSUE THREAD

**Issue by kusma** [mesonbuild/meson#12035]
I get this error when trying to run a devenv after upgrading meson from 1.0 to 1.2:

```
$ meson devenv -C ~/build/mesa/radv
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/mdevenv.py", line 166, in run
    devenv, varnames = get_env(b, dump_fmt)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/mdevenv.py", line 70, in get_env
    env = i.get_env(env, default_fmt)
          ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_env'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?  No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Debian Sid
* what Python version are you using e.g. 3.8.0: Python 3.11.4
* what `meson --version`: 1.2.0
* what `ninja --version` if it's a Ninja build: 1.11.1
