### PR TITLE
Implement an actual set interface for the OrderedSet class. Closes #1670

### LINKED ISSUE #1670: New OrderedSet does not work with python 3.4
Here's a simple unit test:

```
diff --git a/run_unittests.py b/run_unittests.py
index 1d80aac..1251517 100755
--- a/run_unittests.py
+++ b/run_unittests.py
@@ -24,7 +24,7 @@ from pathlib import PurePath
 import mesonbuild.compilers
 import mesonbuild.environment
 import mesonbuild.mesonlib
-from mesonbuild.mesonlib import is_windows, is_osx, is_cygwin
+from mesonbuild.mesonlib import is_windows, is_osx, is_cygwin, OrderedSet
 from mesonbuild.environment import Environment
 from mesonbuild.dependencies import PkgConfigDependency, ExternalProgram
 
@@ -316,6 +316,10 @@ class InternalTests(unittest.TestCase):
         cmd = ['@OUTPUT@.out', 'ordinary', 'strings']
         self.assertRaises(ME, substfunc, cmd, d)
 
+    def test_ordered_set(self):
+        oset = OrderedSet()
+        oset.update(['foo'])
+
 
 class BasePlatformTests(unittest.TestCase):
     def setUp(self):
```

This fails with:

```
======================================================================
ERROR: test_ordered_set (__main__.InternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_unittests.py", line 321, in test_ordered_set
    oset.update(['foo'])
  File "/home/meh/devel/sandbox/meson/mesonbuild/mesonlib.py", line 703, in update
    self[item] = True
  File "/usr/lib64/python3.4/collections/__init__.py", line 68, in __setitem__
    self.__map[key] = link = Link()
AttributeError: 'OrderedSet' object has no attribute '_OrderedDict__map'
```

My python version is 3.4.3.

I'm a bit surprised at this OrderedSet implementation, I would suggest using something like:

https://github.com/hotdoc/hotdoc/blob/master/hotdoc/utils/utils.py#L188

### PR DESCRIPTION
**Pull request by dcbaker**
This uses the ABC's in collections to implement an OrderedSet class.
Internally a list is wrapped so that the ordering is maintained, this
makes some lookups somewhat more expensive than in a real set, but
maintains the interface and behavior of an Set, but with ordering by
first insertion.

This is an alternate version of  #1691 that tries to cut the middle between the two proposed approaches, it provides a full `set` interface, but is implemented from scratch and can meet the APL2 licensing requirements.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
Hm, I wrote a quick script to compare the performance of all three implementations and this one is indeed really slow:

https://da.gd/yE5fK

results:

```
<class '__main__.OrderedSetComposition'> 0:00:00.049330
<class '__main__.OrderedSet'> 0:00:08.183436
<class '__main__.OrderedSetMIT'> 0:00:00.028414
```

**Comment by dcbaker** [comment]
So, there a couple of things. My implementation calls `self.add` within update, replacing that with the contents of update makes it twice as faster (down to five seconds in your test). I'm however, sceptical of the test methodology. creating a set with 30000 items in it with no collisions seems like a rather unlikely scenario.

I Wrote a slightly modified test section:
```python
import timeit

for class_ in OrderedSetComposition, OrderedSet, OrderedSetMIT:
    conc = class_()
    i = 0
    def func(i):
        conc.update(range(i, 25 + i))
        i += 1
    print(class_)
    print(timeit.timeit(lambda: func(i)))
    print()
```
And saw my version perform slightly better than the MIT version, but still considerably worse the the other version.

I did a little more testing and put an `OrderedDict` inside my implementation. It performs update at the basically the same level but provides the full set interface. I'll upload that version.

**Comment by MathieuDuponchelle** [comment]
That's better :)

May I suggest, instead of using an ordered dict as a container, maintaining a circular, doubly linked list, and a simple dict to map a key to a node of the list ?
