### ISSUE TITLE
Error while installing numpy

### ISSUE THREAD

**Issue by Ricc4rdo0107** [mesonbuild/meson#12987]
WARNING: CMake Toolchain: Failed to determine CMake compilers state

      ..\numpy\meson.build:124:13: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

**Comment by eli-schwartz** [comment]
Thank you for reporting that an error occurred.

Could you also tell us what the error was?

**Comment by rgommers** [comment]
That line is `dependency('mkl', ...)`, so I bet it's a bug in my unmerged BLAS dependency code.

@Ricc4rdo0107 a full traceback would be great.

**Comment by KristjanLu** [comment]
I have a similar issue with installing numpy. Maybe my full traceback could help. 


```
Traceback (most recent call last):
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\msetup.py", line 358, in run
          app.generate()
          ~~~~~~~~~~~~^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\msetup.py", line 183, in generate
          return self._generate(env, capture, vslite_ctx)
                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\msetup.py", line 228, in _generate
          intr.run()
          ~~~~~~~~^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 3002, in run
          super().run()
          ~~~~~~~~~~~^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 164, in run
          self.evaluate_codeblock(self.ast, start=1)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 2414, in func_subdir
          self.evaluate_codeblock(codeblock)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
          return self.evaluate_if(cur)
                 ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 301, in evaluate_if
          self.evaluate_codeblock(i.block)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 228, in evaluate_statement
          self.evaluate_foreach(cur)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 472, in evaluate_foreach
          self.evaluate_codeblock(node.block)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
          return self.evaluate_if(cur)
                 ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 306, in evaluate_if
          self.evaluate_codeblock(node.elseblock)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 198, in evaluate_statement
          self.assignment(cur)
          ~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 635, in assignment
          value = self.evaluate_statement(node.value)
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [Previous line repeated 4 more times]
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 109, in wrapped
          ret = f(*wrapped_args, **wrapped_kwargs)
                ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1779, in func_dependency
          d = df.lookup(kwargs)
              ~~~~~~~~~^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreter\dependencyfallbacks.py", line 355, in lookup
          dep = func(kwargs, func_args, func_kwargs)
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\interpreter\dependencyfallbacks.py", line 87, in _do_dependency
          dep = dependencies.find_external_dependency(name, self.environment, kwargs)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\dependencies\detect.py", line 124, in find_external_dependency
          d = c()
              ~^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\dependencies\blas_lapack.py", line 497, in __init__
          super().__init__('OpenBLAS', env, kwargs, language, force_use_global_compilers)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 137, in __init__
          CMakeDependency.class_cmakeinfo[self.for_machine] = self._get_cmake_info(cm_args)
                                                              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 185, in _get_cmake_info
          ret1, out1, err1 = self._call_cmake(cmake_opts, 'CMakePathInfo.txt')
                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 618, in _call_cmake
          build_dir = self._setup_cmake_dir(cmake_file)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
        File "C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 589, in _setup_cmake_dir
          cmake_txt = importlib.resources.read_text('mesonbuild.dependencies.data', cmake_file, encoding = 'utf-8')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'importlib.resources' has no attribute 'read_text'
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad
      Build dir: C:\Users\liisl\AppData\Local\Temp\pip-install-dwqez2oh\numpy_166bc8730c0b4da6b55f8dfd715664ad\.mesonpy-3rf8rq3g
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      Activating VS 17.9.5
      C compiler for the host machine: cl (msvc 19.39.33523 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64")
      C linker for the host machine: link link 14.39.33523.0
      C++ compiler for the host machine: cl (msvc 19.39.33523 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64")
      C++ linker for the host machine: link link 14.39.33523.0
      Cython compiler for the host machine: cython (cython 3.0.10)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (C:\Users\liisl\AppData\Local\Programs\Python\Python313\python.exe)
      Run-time dependency python found: YES 3.13
      Has header "Python.h" with dependency python: YES
      Compiler for C supports arguments -fno-strict-aliasing: NO
      Test features "SSE SSE2 SSE3" : Supported
      Test features "SSSE3" : Supported
      Test features "SSE41" : Supported
      Test features "POPCNT" : Supported
      Test features "SSE42" : Supported
      Test features "AVX" : Supported
      Test features "F16C" : Supported
      Test features "FMA3" : Supported
      Test features "AVX2" : Supported (cached)
      Test features "AVX512F" : Supported
      Test features "AVX512CD" : Supported (cached)
      Test features "AVX512_KNL" : disabled due to AVX512_KNL is disabled due to "msvc compiler does not support it"
      Test features "AVX512_KNM" : disabled due to AVX512_KNM is disabled due to "msvc compiler does not support it"
      Test features "AVX512_SKX" : Supported (cached)
      Test features "AVX512_CLX" : Supported
      Test features "AVX512_CNL" : Supported
      Test features "AVX512_ICL" : Supported
      Test features "AVX512_SPR" : disabled due to AVX512_SPR is disabled due to "msvc compiler does not support it"
      Configuring npy_cpu_dispatch_config.h using configuration
      Message:
      CPU Optimization Options
        baseline:
          Requested : min
          Enabled   : SSE SSE2 SSE3
        dispatch:
          Requested : max -xop -fma4
          Enabled   : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Library m found: NO
      Fetching value of define "__MINGW32__" :
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency scipy-openblas found: NO (tried pkgconfig)
      Run-time dependency mkl found: NO (tried pkgconfig and system)
      Run-time dependency mkl found: NO (tried pkgconfig and system)
      Run-time dependency accelerate found: NO (tried system)
      Found CMake: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.28.0)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state

      ..\numpy\meson.build:124:13: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]
```

**Comment by eli-schwartz** [comment]
@KristjanLu your traceback indicates you're building with alpha releases of Python 3.13. This is known not to work -- there are other tracking tickets for it -- but is expected to be solved by CPython re-adding the removed API (in the next alpha, most likely).

**Comment by rgommers** [comment]
I did add a workaround for that CPython issue in `numpy`'s vendored copy of Meson, but apparently incomplete. The traceback points at this code:
```python
class OpenBLASCMakeDependency(BLASLAPACKMixin, OpenBLASMixin, CMakeDependency):
    def __init__(self, name: str, env: 'Environment', kwargs: T.Dict[str, T.Any],
                 language: T.Optional[str] = None, force_use_global_compilers: bool = False) -> None:
        super().__init__('OpenBLAS', env, kwargs, language, force_use_global_compilers)
```
The BLAS dependency detection via CMake is less well tested (and certainly not on Windows) - it still hits:
```
AttributeError: module 'importlib.resources' has no attribute 'read_text'
```
which is indeed the thing that needs to be restored in CPython. This will start working in the next CPython 3.13 alpha release I think, and it can be worked around now my either making sure `cmake` isn't found or by simply removing the `OpenBLASCMakeDependency` related code.

**Comment by rgommers** [comment]
Just to make @KristjanLu and @Ricc4rdo0107, if you're building `numpy` with CPython 3.13 alpha/main, you are building numpy's `main` branch, right? If you're building 1.26.4: please don't do that, it will not work.

**Comment by rgommers** [comment]
@eli-schwartz could you close this please? I'm pretty sure it's fixed now, and a numpy release supporting Python 3.13 was made.
