### ISSUE TITLE
[regression] GStreamer fails to build with meson 0.58rc1

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#8700]
```
[165/4308] Compiling C object subprojects/gst-plugins-base/gst-libs/gst/gl/libgstgl-1.0.so.0.1900.0.p/gstglwindow.c.o
FAILED: subprojects/gst-plugins-base/gst-libs/gst/gl/libgstgl-1.0.so.0.1900.0.p/gstglwindow.c.o 
ccache cc -Isubprojects/gst-plugins-base/gst-libs/gst/gl/libgstgl-1.0.so.0.1900.0.p -Isubprojects/gst-plugins-base -I../subprojects/gst-plugins-base -Isubprojects/gst-plugins-base/gst-libs -I../subprojects/gst-plugins-base/gst-libs -Isubprojects/gl-headers/abyss -I../subprojects/gl-headers/abyss -Isubprojects/gl-headers/wglext -I../subprojects/gl-headers/wglext -Isubprojects/gstreamer/libs -I../subprojects/gstreamer/libs -Isubprojects/gstreamer -I../subprojects/gstreamer -Isubprojects/orc -I../subprojects/orc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -fvisibility=hidden -fno-strict-aliasing -DG_DISABLE_DEPRECATED -Wmissing-declarations -Wredundant-decls -Wundef -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wvla -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -fPIC -pthread -DHAVE_CONFIG_H -DBUILDING_GST_GL -MD -MQ subprojects/gst-plugins-base/gst-libs/gst/gl/libgstgl-1.0.so.0.1900.0.p/gstglwindow.c.o -MF subprojects/gst-plugins-base/gst-libs/gst/gl/libgstgl-1.0.so.0.1900.0.p/gstglwindow.c.o.d -o subprojects/gst-plugins-base/gst-libs/gst/gl/libgstgl-1.0.so.0.1900.0.p/gstglwindow.c.o -c ../subprojects/gst-plugins-base/gst-libs/gst/gl/gstglwindow.c
In file included from ../subprojects/gst-plugins-base/gst-libs/gst/gl/gstglwindow.c:54:
../subprojects/gst-plugins-base/gst-libs/gst/gl/wayland/gstglwindow_wayland_egl.h:25:10: fatal error: xdg-shell-client-protocol.h: No such file or directory
   25 | #include "xdg-shell-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

GStreamer uses `implicit_include_directories: false` which used to still include current source/build dir, but not anymore. I verified it builds fine with 0.57.2.

**Comment by xclaesse** [comment]
CC @tp-m @nirbheek

**Comment by xclaesse** [comment]
Bisected this to https://github.com/mesonbuild/meson/pull/8574. The change is intentional and makes sense. Maybe a gstreamer bug then...

**Comment by xclaesse** [comment]
Hmm, I was hoping this would affect only GStreamer master so could still be fixed there, but actually the usage of `implicit_include_directories: false` has been backported into 1.18 stable release already.

**Comment by xclaesse** [comment]
@jpakkane It is also suspicious that https://github.com/mesonbuild/meson/pull/8574 only touch the ninja backend. Custom target directory never was added in vs/xcode backends?

**Comment by jpakkane** [comment]
Xcode was definitely not. Not sure about VS, though.

**Comment by xclaesse** [comment]
Let's close this because I think the Meson change makes sense and it has been worked around in GStreamer already by adding `'-I@0@'.format(meson.current_build_dir())` in c_args.

However, I'm wondering if we could still add `include_directories('.', build_only: true)` syntax to avoid having to hardcode the `-I` flag?
