### PR TITLE
Use composition, not inheritance for OrderedSet. Closes #1670.

### LINKED ISSUE #1670: New OrderedSet does not work with python 3.4
Here's a simple unit test:

```
diff --git a/run_unittests.py b/run_unittests.py
index 1d80aac..1251517 100755
--- a/run_unittests.py
+++ b/run_unittests.py
@@ -24,7 +24,7 @@ from pathlib import PurePath
 import mesonbuild.compilers
 import mesonbuild.environment
 import mesonbuild.mesonlib
-from mesonbuild.mesonlib import is_windows, is_osx, is_cygwin
+from mesonbuild.mesonlib import is_windows, is_osx, is_cygwin, OrderedSet
 from mesonbuild.environment import Environment
 from mesonbuild.dependencies import PkgConfigDependency, ExternalProgram
 
@@ -316,6 +316,10 @@ class InternalTests(unittest.TestCase):
         cmd = ['@OUTPUT@.out', 'ordinary', 'strings']
         self.assertRaises(ME, substfunc, cmd, d)
 
+    def test_ordered_set(self):
+        oset = OrderedSet()
+        oset.update(['foo'])
+
 
 class BasePlatformTests(unittest.TestCase):
     def setUp(self):
```

This fails with:

```
======================================================================
ERROR: test_ordered_set (__main__.InternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_unittests.py", line 321, in test_ordered_set
    oset.update(['foo'])
  File "/home/meh/devel/sandbox/meson/mesonbuild/mesonlib.py", line 703, in update
    self[item] = True
  File "/usr/lib64/python3.4/collections/__init__.py", line 68, in __setitem__
    self.__map[key] = link = Link()
AttributeError: 'OrderedSet' object has no attribute '_OrderedDict__map'
```

My python version is 3.4.3.

I'm a bit surprised at this OrderedSet implementation, I would suggest using something like:

https://github.com/hotdoc/hotdoc/blob/master/hotdoc/utils/utils.py#L188

### PR DESCRIPTION
**Pull request by jpakkane**
Alternative version of #1680.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
That's a solution, I thought my solution was more appropriate because it's actually a set, with set operators etc :)

**Comment by jpakkane** [comment]
I am _not_ a fan of embedding third party code, especially one that has a different license.

**Comment by MathieuDuponchelle** [comment]
Well MIT license wouldn't involve any issue for meson licensing, but as you like I guess, I do like reusing solutions that work as long as they don't force me to do more than adding a license notice :)

**Comment by dcbaker** [comment]
I've created an alternative proposal that composes a new OrderedSet around a list. It has a full set based interface and uses the standard `collections.MutableSet` ABC to get most of the implementation for free. It gets the advantages of working on 3.4 (I developed and tested it on 3.4), I wrote it from scratch so it can be licensed APL2, it's not a lot of code, and it exposes the full `set` interface. The only drawback is that since it wraps a list it inherits some of the performance costs of lists for doing arbitrary insertions and deletions.

**Comment by MathieuDuponchelle** [comment]
That's better :)

May I suggest, instead of using an ordered dict as a container, maintaining a circular, doubly linked list, and a simple dict to map a key to a node of the list ?
