### ISSUE TITLE
systemd build broken by #5065

### ISSUE THREAD

**Issue by jon-turney** [mesonbuild/meson#5113]
See https://travis-ci.org/jon-turney/meson-corpus-test/jobs/508033325#L1596

Bisecting meson lands on commit 07818dac6acc7a805548be4b605320dd27de126c

I think this may be related somehow to `-lrt` being de-duplicated in a linking command line?

**Comment by jon-turney** [comment]
```console
jon@bionic:~/src$ git clone https://github.com/jon-turney/meson-corpus-test-update
[...]
jon@bionic:~/src$ cd meson-corpus-test-update/
jon@bionic:~/src/meson-corpus-test-update$ ./run systemd
[...]
[584/1778] Linking target libnss_myhostname.so.2.
FAILED: libnss_myhostname.so.2 
cc  -o libnss_myhostname.so.2 'nss_myhostname@sha/src_nss-myhostname_nss-myhostname.c.o' 'nss_myhostname@sha/src_libsystemd_disable-mempool.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libnss_myhostname.so.2 -Wl,-z,relro -Wl,-z,now src/libsystemd/libsystemd_static.a src/basic/libbasic.a -Wl,-z,nodelete -shared -Wl,--version-script=/systemd/src/nss-myhostname/nss-myhostname.sym -Wl,--undefined -lrt /usr/lib/i386-linux-gnu/libcap.so /usr/lib/i386-linux-gnu/libselinux.so -lm -Wl,--end-group -pthread '-Wl,-rpath,$ORIGIN/src/libsystemd:$ORIGIN/src/basic' -Wl,-rpath-link,/systemd/_build/src/libsystemd:/systemd/_build/src/basic 
src/libsystemd/libsystemd_static.a(sd-daemon_sd-daemon.c.o): In function `sd_is_mq':
/systemd/_build/../src/libsystemd/sd-daemon/sd-daemon.c:411: undefined reference to `mq_getattr'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
jon@bionic:~/src/meson-corpus-test-update$ ./run systemd --commit 5f00c302
[...]
[1777/1778] Installing files.
[...]
```

**Comment by jon-turney** [comment]
This should probably be tagged for 0.50.1, as #5065 was.

**Comment by jpakkane** [comment]
It may be that this is not a bug in Meson after all. Systemd has this in its build definition files:

```meson
                        link_args : ['-Wl,-z,nodelete',
                                     '-shared',
                                     '-Wl,--version-script=' + version_script_arg,
                                     '-Wl,--undefined'],
```

The last one of these is wrong from what I can tell. Ld's man page says the following:

```
       -u symbol
       --undefined=symbol
           Force symbol to be entered in the output file as an undefined symbol.  Doing this may, for example, trigger linking of additional modules from standard libraries.  -u may
           be repeated with different option arguments to enter additional undefined symbols.  This option is equivalent to the "EXTERN" linker script command.

           If this option is being used to force additional modules to be pulled into the link, and if it is an error for the symbol to remain undefined, then the option
           --require-defined should be used instead.
```

This would imply that it always requires an argument, which this does not pass. Thus it will grab the next argument on the command line as its argument. Before it took one of the many `-lrt` args (presumably) and now it grabs something other random linker argument and things break.

This patch to systemd makes it compile:

```
diff --git a/meson.build b/meson.build
index 287125f010..79195c9748 100644
--- a/meson.build
+++ b/meson.build
@@ -1606,8 +1606,7 @@ foreach tuple : [['myhostname', 'ENABLE_NSS_MYHOSTNAME'],
                         # Note that we link NSS modules with '-z nodelete' so that mempools never get orphaned
                         link_args : ['-Wl,-z,nodelete',
                                      '-shared',
-                                     '-Wl,--version-script=' + version_script_arg,
-                                     '-Wl,--undefined'],
+                                     '-Wl,--version-script=' + version_script_arg],
                         link_with : [libsystemd_static,
                                      libbasic],
                         dependencies : [threads,
```

Ping @keszybz

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/pull/12232

**Comment by jpakkane** [comment]
Thanks. Closing this.

**Comment by jon-turney** [comment]
Thanks
