### ISSUE TITLE
Cannot compile Windows RC file with Meson git

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#15206]
**Describe the bug**

Compiling GLib on Windows with MSVC fails with the following error:

```
Compiling C object glib/glib.rc_i.p/glib.rc.i
FAILED: glib/glib.rc_i.p/glib.rc.i
"cl" "/EP" "/P" "-Iglib\glib.rc_i.p" "-Iglib" "-I..\glib\glib" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W4" "/O2" "/Z7" "/FIglib/msvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DUNICODE" "-D_UNICODE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-DRC_INVOKED" "/Fdglib\glib.rc_i.p\glib.rc.pdb" /Figlib/glib.rc_i.p/glib.rc.i "/c" glib/glib.rc
glib.rc
glib/glib.rc: fatal error C1083: Cannot open include file: 'glib/msvc_recommended_pragmas.h': No such file or directory
ninja: build stopped: subcommand failed.
```

**To Reproduce**

* Open either CMD or PowerShell
* `python C:\path\to\meson-git\meson.py setup ..\glib --vsenv`
* `python C:\path\to\meson-git\meson.py compile`

**Expected behavior**

Compilation should succeed as in Meson 1.9.1

**system parameters**
* Native build
* Windows 11
* Python 3.14
* Meson master
* ninja 1.13.1

**Comment by lb90** [comment]
This was bisected to 632115ecff3bd7f9cb519098e04e0467b0cfd3a1

**Comment by bonzini** [comment]
@bruchar1

**Comment by bruchar1** [comment]
It seems to be an include path problem.

**Comment by dcbaker** [comment]
(Adding branches and tags to help make sure this doesn't get missed before 1.10.0)

**Comment by bruchar1** [comment]
I was able to reproduce. However, I'm not sure to understand how to solve it...

**Comment by lb90** [comment]
Hi @bruchar1, thanks for looking into this! :)

I think we can modify things on the GLib side if needed. Could you explain what's happening under the hood?

**Comment by lb90** [comment]
I think that:

* In Meson 1.9.1, options added via `add_project_options('...', language: 'c')` do not influence compilation of RC files in any way
* In Meson git, options added via `add_project_options('...', language: 'c')` end up in the depfile target for RC files

Perhaps we can invoke the preprocessor via `CUSTOM_COMMAND` rather than `c_PREPROCESSOR`?

**Comment by bonzini** [comment]
That's a separate issue, which is not as serious a bug. But if there's no idea on how to fix this the original PR should be reverted.

**Comment by bruchar1** [comment]
The original problem seems about messed up include paths.

I understand that the preprocessor will use options from the project. But how does this cause problems to the rc generation? The goal of the preprocessor command is to detect dependencies of the rc file.

**Comment by bonzini** [comment]
That other bug seems to be a problem with GCC?

**Comment by bonzini** [comment]
It still needs a workaround even if it's a GCC internal error for real, though.

**Comment by bruchar1** [comment]
I don't understand how gcc can be related to a hack specific to the rc.exe Windows resource compiler.

**Comment by bonzini** [comment]
From #15215:

```
"C:\mingw64\bin\windres.EXE" "-ID:/a/meson/meson/test cases/windows/15 resource scripts with duplicate filenames/exe3/." "-ID:/a/meson/meson/b a463e29691/exe3/." "../test cases/windows/15 resource scripts with duplicate filenames/exe3/src_exe/version.rc" "exe3/exe3_src_exe_version.rc_version.o" "--preprocessor-arg=-MD" "--preprocessor-arg=-MQexe3/exe3_src_exe_version.rc_version.o" "--preprocessor-arg=-MFexe3/exe3_src_exe_version.rc_version.o.d"
gcc: internal compiler error: in do_spec_1, at gcc.cc:6214
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/niXman/mingw-builds> for instructions.
C:\mingw64\bin\windres.EXE: preprocessing failed.
```

**Comment by bruchar1** [comment]
Ok. I will try to have a look (I don't have time right now...). But the preprocessor hack should not be used for windres. It is only for rc.exe.

**Comment by bonzini** [comment]
Ah, the log says it:

```
WARNING: Argument '-ID:\\a\\meson\\meson\\test cases\\windows\\15 resource scripts with duplicate filenames\\a\\.' has a space which may not work with windres due to a MinGW bug: https://sourceware.org/bugzilla/show_bug.cgi?id=4933
```

The problem is in the new -I argument. Maybe something like this:

```diff
diff --git a/mesonbuild/modules/windows.py b/mesonbuild/modules/windows.py
index 17fc8abe4..1207f1ebb 100644
--- a/mesonbuild/modules/windows.py
+++ b/mesonbuild/modules/windows.py
@@ -149,7 +149,6 @@ class WindowsModule(ExtensionModule):
                     build.IncludeDirs('', [], False, [os.path.join('@BUILD_ROOT@', self.interpreter.backend.get_target_dir(d))])
                 ])
         include_directories = self.interpreter.extract_incdirs(kwargs)
-        extra_args += state.get_include_args(include_directories)
 
         rescomp, rescomp_type = self._find_resource_compiler(state)
         if rescomp_type == ResourceCompilerType.rc:
@@ -157,21 +156,29 @@ class WindowsModule(ExtensionModule):
             # format, which can be passed directly to LINK (apparently LINK uses
             # CVTRES internally to convert this to a COFF object)
             suffix = 'res'
-            res_args = extra_args + ['/nologo', '/fo@OUTPUT@', '@INPUT@']
+            res_args = ['/nologo', '/fo@OUTPUT@', '@INPUT@']
+
+            # needed for the preprocessor target
+            self_dir = build.IncludeDirs(state.subdir, ['.'], False)
+            if self_dir not in include_directories:
+                include_directories.append(self_dir)
         elif rescomp_type == ResourceCompilerType.windres:
             # ld only supports object files, so windres is used to generate a
             # COFF object
             suffix = 'o'
-            res_args = extra_args + ['@INPUT@', '@OUTPUT@']
+            res_args = ['@INPUT@', '@OUTPUT@']
+        else:
+            suffix = 'o'
+            res_args = ['@INPUT@', '-o', '@OUTPUT@']
 
+        extra_args += state.get_include_args(include_directories)
+        if rescomp_type == ResourceCompilerType.windres:
             m = 'Argument {!r} has a space which may not work with windres due to ' \
                 'a MinGW bug: https://sourceware.org/bugzilla/show_bug.cgi?id=4933'
             for arg in extra_args:
                 if ' ' in arg:
                     mlog.warning(m.format(arg), fatal=False)
-        else:
-            suffix = 'o'
-            res_args = extra_args + ['@INPUT@', '-o', '@OUTPUT@']
+        res_args = extra_args + res_args
 
         res_targets: T.List[build.CustomTarget] = []
 
```

**Comment by bonzini** [comment]
Hmm, maybe not.  I think the suggestion not to use c_PREPROCESSOR is better.

**Comment by bruchar1** [comment]
- The initial bug is about a missing include directory. Using a custom_target instead of the c_PREPROCESSOR would change nothing about it
- The gcc bug seems to be an unrelated side effect. It is triggered by adding an include directory to the windres command. It says "preprocessing failed", but it has nothing to do with the preprocessor hack added for rc. We can trigger the same bug by adding '.' to include_directories of the win.compile_resources command in the build file.
- Not adding the current dir when using windres make the test fail on cygwin.

Therefore, I propose to:
- add the missing include dir, as I did in the draft PR
- disable the failing test with gcc on Windows
- open another bug for that failing test

**Comment by bonzini** [comment]
> The initial bug is about a missing include directory. Using a custom_target instead of the c_PREPROCESSOR would change nothing about it

What requires the directory is a /FI: option that is added by c_PREPROCESSOR. If you use a custom target that doesn't add project and global cc arguments, then that option goes away.

OTOH the GCC bug shows that it's better not to add that directory by default.

**Comment by bruchar1** [comment]
Ok, now I understand what you mean.

But:
- a rc file should be able to include a header file in the same directory without the need of explicitly setting an include_directory
- I'm not sure why project or global options should not influence the resource compiler
- the test I added shows that compile_resources was not able to deal with generated rc files because of that missing include path

**Comment by lb90** [comment]
Hi! Took a look at this

So, here's what happens:
* GLib adds a `/FIglib/msvc_recommended_pragmas.h` argument globally using `add_project_arguments`: https://gitlab.gnome.org/GNOME/glib/-/blob/2.87.0/meson.build?ref_type=tags#L57
* GLib then creates an `include_directories` for the root of the project: https://gitlab.gnome.org/GNOME/glib/-/blob/2.87.0/meson.build?ref_type=tags#L111. This is necessary for the forced include above to work
* That `inc` object is added to every build target, for example: https://gitlab.gnome.org/GNOME/glib/-/blob/2.87.0/glib/meson.build?ref_type=tags#L415. That's what's missing in the rc's preprocessing target

**Comment by lb90** [comment]
For example, say you have

```
C:\glib-source
C:\glib-build
```

All that's needed to make the rc's preprocessing work is to add the `-I..\glib-source` argument.

**Comment by bonzini** [comment]
Fixed by #15299
