### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Bug-Fighter** [mesonbuild/meson#14751]
**Describe the bug**
xemu build fine with meson 1.7.0. I upgrade meson to 1.8.2. Then I try to build last xemu source code (0.8.85) with the following command :
`CFLAGS="-march=native" CXXFLAGS="-march=native" ./build.sh --prefix=/usr`

It produces those messages :

`Using './build' as the directory for build output`
`python determined to be '/usr/bin/python3'`
`python version: Python 3.10.11`
`mkvenv: Creating non-isolated virtual environment at 'pyvenv'`
`mkvenv: checking for meson>=1.5.0`
`mkvenv did not complete successfully:`
`Traceback (most recent call last):`
 ` File "/home/paul/rpmbuild/BUILD/xemu-0.8.85/python/scripts/mkvenv.py", line 866, in main`
   ` ensure_group(`
 ` File "/home/paul/rpmbuild/BUILD/xemu-0.8.85/python/scripts/mkvenv.py", line 766, in ensure_group`
  `result = _do_ensure(to_install, online, wheels_dir)`
 `File "/home/paul/rpmbuild/BUILD/xemu-0.8.85/python/scripts/mkvenv.py", line 686, in _do_ensure`
    `or not matcher.match(distlib.version.LegacyVersion(dist.version))`
 ` File "/usr/lib/python3.10/site-packages/distlib/version.py", line 32, in __init__`
   ` self._string = s = s.strip()`
`AttributeError: 'NoneType' object has no attribute 'strip'`

**To Reproduce**

- loading xemu source code
-` git clone --recurse-submodules https://github.com/xemu-project/xemu.git`
- building it as usual
- `cd xemu`
- `./build.sh`

**Expected behavior**
Get a fine building of this source code as meson 1.7.0 did.

**system parameters**
- Native build
- OS : Mageia 9
- Python : 3.10.11
- meson : 1.8.2
- ninja : 1.11.1

**Comment by bonzini** [comment]
That happens before meson is invoked, so closing the bug. I will look at it later as a QEMU developer but this is not a meson bug.
