### ISSUE TITLE
GLib fails to build with meson 1.6 and --default-library both

### ISSUE THREAD

**Issue by ziyao233** [mesonbuild/meson#13850]
Building glib 2.82.2 with meson 1.6, with `--default-library both` specified during configuration, fails. This could be reproduced both on ArchLinux and eweOS[1].

On ArchLinux, the failure looks like

```
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../lib/libgio-2.0.so: undefined reference to symbol 'g_strv_get_type'
/usr/bin/ld: /usr/lib/libgobject-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['cc', '-o', '/home/ziyao/glib2/src/build/tmp-introspect1ubvf4n_/GLib-2.0', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fno-plt', '-fexceptions', '-Wp,-D_FORTIFY_SOURCE=3', '-Wformat', '-Werror=format-security', '-fstack-clash-protection', '-fcf-protection', '-fno-omit-frame-pointer', '-mno-omit-leaf-frame-pointer', '-g', '-ffile-prefix-map=/home/ziyao/glib2/src=/usr/src/debug/glib2', '-flto=auto', '-g3', '-ffat-lto-objects', '/home/ziyao/glib2/src/build/tmp-introspect1ubvf4n_/GLib-2.0.o', '-L.', '-Wl,-rpath,.', '-Wl,--no-as-needed', '-L/home/ziyao/glib2/src/build/girepository/introspection', '-Wl,-rpath,/home/ziyao/glib2/src/build/girepository/introspection', '-L/home/ziyao/glib2/src/build/glib', '-Wl,-rpath,/home/ziyao/glib2/src/build/glib', '-lgobject-2.0', '-lglib-2.0', '-lm', '-lsysprof-capture-4', '-lpcre2-8', '-lgirepository-1.0', '-lgobject-2.0', '-lglib-2.0', '-L/home/ziyao/glib2/src/build/gio', '-lgio-2.0', '-L/home/ziyao/glib2/src/build/gobject', '-lgobject-2.0', '-Wl,--export-dynamic', '-L/home/ziyao/glib2/src/build/gmodule', '-lgmodule-2.0', '-pthread', '-L/home/ziyao/glib2/src/build/glib', '-lglib-2.0', '-Wl,-O1', '-Wl,--sort-common', '-Wl,-z,relro', '-Wl,-z,now', '-Wl,-z,pack-relative-relocs', '-flto=auto']' returned non-zero exit status 1.
[1148/1696] Compiling C object gio/tes...odegen-generated-min-required-2-64.c.o
ninja: build stopped: subcommand failed.
```

Glib is configured as

```
meson setup --prefix /usr \
	--libexecdir lib		\
	--sbindir bin			\
	--buildtype plain		\
	--auto-features enabled		\
	--wrap-mode nodownload		\
	-D b_pie=true			\
	-D python.bytecompile=1		\
	glib build			\
	--default-library both		\
	-D documentation=true		\
	-D dtrace=disabled		\
	-D glib_debug=disabled		\
	-D introspection=enabled	\
	-D man-pages=enabled		\
	-D selinux=disabled		\
	-D sysprof=enabled		\
	-D systemtap=disabled
```

a full buildlog could be obtained here[2] and the buildscript could be obtained here[3].

On eweOS, the failure looks like

```
[   71s] mold: error: undefined symbol: ffi_type_sint64
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_prep_cif
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_type_sint32
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_type_uint64
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_type_double
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_call
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_type_uint32
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_type_void
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] mold: error: undefined symbol: ffi_type_pointer
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced 2 more times
[   71s] mold: error: undefined symbol: ffi_type_float
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(value_to_ffi_type)
[   71s] >>> referenced by ld-temp.o
[   71s] >>>               /tmp/lto-llvm-97eaf3.o:(g_cclosure_marshal_generic_va)
[   71s] cc: error: linker command failed with exit code 1 (use -v to see invocation)
[   71s] linking of temporary binary failed: Command '['cc', '-o', '/usr/src/packages/BUILD/glib/src/build/tmp-introspectzd7470wy/GLib-2.0', '-Os', '-pipe', '-fno-plt', '-march=x86-64', '-fstack-clash-protection', '-fcf-protection', '-flto=auto', '/usr/src/packages/BUILD/glib/src/build/tmp-introspectzd7470wy/GLib-2.0.o', '-L.', '-Wl,-rpath,.', '-Wl,--no-as-needed', '-L/usr/src/packages/BUILD/glib/src/build/girepository/introspection', '-Wl,-rpath,/usr/src/packages/BUILD/glib/src/build/girepository/introspection', '-L/usr/src/packages/BUILD/glib/src/build/glib', '-Wl,-rpath,/usr/src/packages/BUILD/glib/src/build/glib', '-lgobject-2.0', '-lglib-2.0', '-lm', '-lpcre2-8', '-lgirepository-1.0', '-lgobject-2.0', '-lglib-2.0', '-L/usr/src/packages/BUILD/glib/src/build/gio', '-lgio-2.0', '-L/usr/src/packages/BUILD/glib/src/build/gobject', '-lgobject-2.0', '-Wl,--export-dynamic', '-L/usr/src/packages/BUILD/glib/src/build/gmodule', '-lgmodule-2.0', '-pthread', '-L/usr/src/packages/BUILD/glib/src/build/glib', '-lglib-2.0', '-flto=auto']' returned non-zero exit status 1.
```

Here is a full build log[4], the buildscript could be found here[5]. libffi is not correctly linked in this case, though it's specified as girepository's dependency[6].

Though these two failures look different, I guess they are related since they are both introduced by meson between `8a641ca ("Fix pkgconfig.generate handling of BothLibraries dependencies")`[7] and `7b3169f ("allow internal_dependency object to carry both_lib")`[8] and could be avoided by remove `--default-library both` flag during `meson setup`. I cannot bisect a precise bad commit, since mesonbuild between these commits is broken and unable to configure glib correctly.

This issue has been posted on GNOME gitlab[9], but I repost it here since I'm not familiar with meson and cannot figure out such behavior breakage is intended or a bug. Thanks for your time. 

[1]: https://os.ewe.moe
[2]: https://bin.disroot.org/?6db6b33fa4c548cc#CrqBxyXuWDF9bPB8c3GFSgajNyHvGwpCcGtGt3fxiyhQ 
[3]: https://gitlab.archlinux.org/archlinux/packaging/packages/glib2/-/blob/1826c3721d3372e57609544f8d596e0711951489/PKGBUILD
[4]: https://bin.disroot.org/?f87899038bdd2381#CjNno1pH42wN16RArEeqvQvQRDA4zYqHJeKjMezfM6ft
[5]: https://github.com/eweOS/packages/blob/bbd2fe378ba57c1e78465044ee71cc66f9f506e0/PKGBUILD
[6]: https://gitlab.gnome.org/GNOME/glib/-/blob/0828714bd46d2606ca753355df408c6326cc4933/girepository/meson.build#L142-146
[7]: https://github.com/mesonbuild/meson/commit/8a641cac5f7fd01c5e213c170c1babc18088369d
[8]: https://github.com/mesonbuild/meson/commit/7b3169f464810dfed0daf3075a5a6e5ed91dbc9b
[9]: https://gitlab.gnome.org/GNOME/glib/-/issues/3515

**Comment by dcbaker** [comment]
@bruchar1, @xclaesse: I think this is the same issue that you're working on?

**Comment by smcv** [comment]
Building 2.83.0 in Debian unstable, with Meson 1.6.0 and `--default-library both`, did not reproduce this issue - so there must be a bit more to it than what's stated in the issue title.

It might be relevant that @ziyao233 seems to be using LTO on both of the affected builds, while Debian is not?

**Comment by heftig** [comment]
Indeed, LTO (either via external CFLAGS or via `-D b_lto=true`) is required to trigger this bug.

**Comment by heftig** [comment]
It also seems to require sufficient parallelism - building on a 48-core server triggers it but not a 4p+8e-core laptop.

**Comment by heftig** [comment]
This change makes GLib build again:

```diff
diff --git c/mesonbuild/modules/gnome.py i/mesonbuild/modules/gnome.py
index e0c1214d0..5a7160d60 100644
--- c/mesonbuild/modules/gnome.py
+++ i/mesonbuild/modules/gnome.py
@@ -667,6 +667,9 @@ class GnomeModule(ExtensionModule):
                     assert isinstance(girdir, str), 'for mypy'
                     gi_includes.update([girdir])
             if isinstance(dep, InternalDependency):
+                # Ensure BothLibraries are resolved
+                dep = dep.get_as_shared(recursive=True)
+
                 cflags.update(dep.get_compile_args())
                 cflags.update(state.get_include_args(dep.include_directories))
                 for lib in dep.libraries:
```

But I'm not sure it's right.
