### PR TITLE
mesondata: fix mypy warnings

### PR DESCRIPTION
**Pull request by dcbaker**
Mypy is wrong because typeshed is wrong.

### CODE REVIEW

File: mesonbuild/mesondata.py [hunk 1]
```diff
@@ -25,7 +25,7 @@ def write_once(self, path: Path) -> None:
 
     def write_to_private(self, env: 'Environment') -> Path:
         try:
-            resource = importlib.resources.files('mesonbuild') / self.path
+            resource = importlib.resources.files('mesonbuild') / self.path.as_posix()
```
Comment (eli-schwartz) [inline mesonbuild/mesondata.py]: This is a silly fix IMO because it makes the following code unreachable. What's the specific reason mypy doesn't like this?

Comment (dcbaker) [reply mesonbuild/mesondata.py]: You can't `/` a `Traversable` and a `PurePath`, it wants ~~either~~ a string ~~or a concrete `Path`~~

Comment (dcbaker) [reply mesonbuild/mesondata.py]: I'm actually super confused on this now.

Comment (dcbaker) [reply mesonbuild/mesondata.py]: Here's the (3.13) definition of `Traversable.__truediv__`:
```python
StrPath: TypeAlias = str | os.PathLike[str]
def __truediv__(self, child: StrPath) -> "Traversable": ...
```
`PurePath` is an instance of `os.PathLike[str]`.

So I'm super confused on why this is showing up as an issue.

**Comment by dcbaker** [comment]
I think this is a typeshed issue

https://github.com/python/typeshed/pull/15108

**Comment by dcbaker** [comment]
@eli-schwartz: updated with an ignore because this is a bad warning from a bug in typeshed.

**Comment by eli-schwartz** [comment]
Nice.

**Comment by jpakkane** [comment]
Seems to need tweaking.

```
mesonbuild/mesondata.py:30: error: Unused "type: ignore" comment  [unused-ignore]
mesonbuild/mesondata.py:30:24: error: Module has no attribute "files"  [attr-defined]
mesonbuild/mesondata.py:30:24: note: Error code "attr-defined" not covered by "type: ignore" comment
```

**Comment by dcbaker** [comment]
Yeah, I think we need to have a version check instead of a `try/except`

**Comment by eli-schwartz** [comment]
IIRC I wrote this and did it this way because a simple version check was wrong -- older versions of python didn't support the good path, and newer versions of python support the good path only when not running from a zipapp install. Trying to remember the details of what the thought process was...

File: mesonbuild/mesondata.py [hunk 2]
```diff
@@ -24,13 +25,16 @@ def write_once(self, path: Path) -> None:
...
 
     def write_to_private(self, env: 'Environment') -> Path:
-        try:
-            resource = importlib.resources.files('mesonbuild') / self.path
-            if isinstance(resource, Path):
-                return resource
-        except AttributeError:
-            # fall through to python 3.7 compatible code
-            pass
+        if sys.version_info >= (3, 10):
```
Comment (eli-schwartz) [inline mesonbuild/mesondata.py]: It should be fine with 3.9 too?

Comment (eli-schwartz) [reply mesonbuild/mesondata.py]: The error in the previous lint run was occurring for 3.7 and 3.8 only -- and it said "files() doesn't exist".

Comment (dcbaker) [reply mesonbuild/mesondata.py]: Yup, you're right. For some reason I read the docs as saying this only worked with 3.10

**Comment by dcbaker** [comment]
I think we have consensus on this? I'm planning to merge this Friday unless there's objection.
