### ISSUE TITLE
meson-1.3.0 regression: SIZEOF_OFF_T is not defined anymore after updating from 1.2.3

### ISSUE THREAD

**Issue by XVilka** [mesonbuild/meson#12531]
**Describe the bug**
In libzip-1.9.2 subproject of Rizin the `compat.h` header doesn't have `SIZEOF_OFF_T` 

```
FAILED: subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add.c.o 
clang -Isubprojects/libzip-1.9.2/liblibzip.a.p -Isubprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2/lib -Isubprojects/zlib-1.3 -I../subprojects/zlib-1.3 -I../subprojects/xz-5.4.3/src/liblzma/api -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -fPIC -DLZMA_API_STATIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add.c.o -c ../subprojects/libzip-1.9.2/lib/zip_add.c
In file included from ../subprojects/libzip-1.9.2/lib/zip_add.c:36:
In file included from ../subprojects/libzip-1.9.2/lib/zipint.h:37:
In file included from subprojects/libzip-1.9.2/config.h:4:
subprojects/libzip-1.9.2/zipconf.h:18:18: error: expected value in expression
#if HAVE_LIMITS_H
                 ^
In file included from ../subprojects/libzip-1.9.2/lib/zip_add.c:36:
In file included from ../subprojects/libzip-1.9.2/lib/zipint.h:39:
../subprojects/libzip-1.9.2/lib/compat.h:136:18: error: invalid token at start of a preprocessor expression
#if SIZEOF_OFF_T == 8
                 ^
../subprojects/libzip-1.9.2/lib/compat.h:139:20: error: invalid token at start of a preprocessor expression
#elif SIZEOF_OFF_T == 4
                   ^
../subprojects/libzip-1.9.2/lib/compat.h:142:20: error: invalid token at start of a preprocessor expression
#elif SIZEOF_OFF_T == 2
                   ^
../subprojects/libzip-1.9.2/lib/compat.h:146:2: error: unsupported size of off_t
#error unsupported size of off_t
 ^
5 errors generated.
[202/2060] Compiling C object subprojects/libzip-1.9.2/liblibzip.a.p/meson-generated_.._zip_err_str.c.o
FAILED: subprojects/libzip-1.9.2/liblibzip.a.p/meson-generated_.._zip_err_str.c.o 
clang -Isubprojects/libzip-1.9.2/liblibzip.a.p -Isubprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2/lib -Isubprojects/zlib-1.3 -I../subprojects/zlib-1.3 -I../subprojects/xz-5.4.3/src/liblzma/api -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -fPIC -DLZMA_API_STATIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/meson-generated_.._zip_err_str.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/meson-generated_.._zip_err_str.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/meson-generated_.._zip_err_str.c.o -c subprojects/libzip-1.9.2/zip_err_str.c
In file included from subprojects/libzip-1.9.2/zip_err_str.c:5:
In file included from ../subprojects/libzip-1.9.2/lib/zipint.h:37:
In file included from subprojects/libzip-1.9.2/config.h:4:
subprojects/libzip-1.9.2/zipconf.h:18:18: error: expected value in expression
#if HAVE_LIMITS_H
                 ^
In file included from subprojects/libzip-1.9.2/zip_err_str.c:5:
In file included from ../subprojects/libzip-1.9.2/lib/zipint.h:39:
../subprojects/libzip-1.9.2/lib/compat.h:136:18: error: invalid token at start of a preprocessor expression
#if SIZEOF_OFF_T == 8
                 ^
../subprojects/libzip-1.9.2/lib/compat.h:139:20: error: invalid token at start of a preprocessor expression
#elif SIZEOF_OFF_T == 4
                   ^
../subprojects/libzip-1.9.2/lib/compat.h:142:20: error: invalid token at start of a preprocessor expression
#elif SIZEOF_OFF_T == 2
                   ^
../subprojects/libzip-1.9.2/lib/compat.h:146:2: error: unsupported size of off_t
#error unsupported size of off_t
 ^
5 errors generated.
[203/2060] Compiling C object subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add_dir.c.o
FAILED: subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add_dir.c.o 
clang -Isubprojects/libzip-1.9.2/liblibzip.a.p -Isubprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2/lib -Isubprojects/zlib-1.3 -I../subprojects/zlib-1.3 -I../subprojects/xz-5.4.3/src/liblzma/api -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -fPIC -DLZMA_API_STATIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add_dir.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add_dir.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_add_dir.c.o -c ../subprojects/libzip-1.9.2/lib/zip_add_dir.c
In file included from ../subprojects/libzip-1.9.2/lib/zip_add_dir.c:36:
In file included from ../subprojects/libzip-1.9.2/lib/zipint.h:37:
In file included from subprojects/libzip-1.9.2/config.h:4:
subprojects/libzip-1.9.2/zipconf.h:18:18: error: expected value in expression
#if HAVE_LIMITS_H
                 ^
In file included from ../subprojects/libzip-1.9.2/lib/zip_add_dir.c:36:
In file included from ../subprojects/libzip-1.9.2/lib/zipint.h:39:
../subprojects/libzip-1.9.2/lib/compat.h:136:18: error: invalid token at start of a preprocessor expression
#if SIZEOF_OFF_T == 8
                 ^
../subprojects/libzip-1.9.2/lib/compat.h:139:20: error: invalid token at start of a preprocessor expression
#elif SIZEOF_OFF_T == 4
                   ^
../subprojects/libzip-1.9.2/lib/compat.h:142:20: error: invalid token at start of a preprocessor expression
#elif SIZEOF_OFF_T == 2
                   ^
../subprojects/libzip-1.9.2/lib/compat.h:146:2: error: unsupported size of off_t
#error unsupported size of off_t
 ^
5 errors generated.
```

See files:
- https://github.com/rizinorg/rizin/blob/dev/subprojects/packagefiles/libzip-1.9.2/cmake-zipconf.h.in
- https://github.com/rizinorg/rizin/blob/dev/subprojects/packagefiles/libzip-1.9.2/meson.build

**To Reproduce**
1. `git clone https://github.com/rizinorg/rizin`
2. `meson setup build` (with 1.3.0 meson)
3. `ninja -C build`

**Expected behavior**
No error - same behavior as in 1.2.3

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? - native build
* what operating system - any
* what Python version are you using  - any
* what `meson --version` (1.3.0 vs previously 1.2.3)
* what `ninja --version` if it's a Ninja build - any

**Comment by QuLogic** [comment]
I think you want to link to [`cmake-config.h.in`](https://github.com/rizinorg/rizin/blob/dev/subprojects/packagefiles/libzip-1.9.2/cmake-config.h.in), not `cmake-zipconf.h.in`, which doesn't have any `#cmakedefine SIZEOF_OFF_T` or `${SIZEOF_OFF_T}` in it.

**Comment by QuLogic** [comment]
And also, posting the configuration stage would be better than the compile output.

**Comment by QuLogic** [comment]
A quick bisect of the libzip wrap points to b91244c3b7f77578d601502628bceb9e92183387 / #11328.

**Comment by QuLogic** [comment]
Looking at https://cmake.org/cmake/help/latest/command/configure_file.html though, I think the `cmake-config.h.in` was wrong? It appears that you need to put a value in if you want the define to have a value, and Meson was doing the wrong thing earlier. (The `#cmakedefine` only toggles whether it becomes `#define` or `#undef`, not whether it has a value.)

**Comment by QuLogic** [comment]
This works with 1.2.3 and 1.3.0:
```
diff --git a/subprojects/packagefiles/libzip-1.9.2/cmake-config.h.in b/subprojects/packagefiles/libzip-1.9.2/cmake-config.h.in
index 50dd019296..9e1f612fa6 100644
--- a/subprojects/packagefiles/libzip-1.9.2/cmake-config.h.in
+++ b/subprojects/packagefiles/libzip-1.9.2/cmake-config.h.in
@@ -46,8 +46,8 @@
 #cmakedefine HAVE_STRINGS_H
 #cmakedefine HAVE_UNISTD_H
 #cmakedefine HAVE_WINDOWS_CRYPTO
-#cmakedefine SIZEOF_OFF_T
-#cmakedefine SIZEOF_SIZE_T
+#cmakedefine SIZEOF_OFF_T @SIZEOF_OFF_T@
+#cmakedefine SIZEOF_SIZE_T @SIZEOF_SIZE_T@
 #cmakedefine HAVE_DIRENT_H
 #cmakedefine HAVE_FTS_H
 #cmakedefine HAVE_NDIR_H
diff --git a/subprojects/packagefiles/libzip-1.9.2/cmake-zipconf.h.in b/subprojects/packagefiles/libzip-1.9.2/cmake-zipconf.h.in
index 203ebeb499..9afce7ae61 100644
--- a/subprojects/packagefiles/libzip-1.9.2/cmake-zipconf.h.in
+++ b/subprojects/packagefiles/libzip-1.9.2/cmake-zipconf.h.in
@@ -15,7 +15,7 @@

 #cmakedefine HAVE_LIMITS_H

-#if HAVE_LIMITS_H
+#ifdef HAVE_LIMITS_H
 #include <limits.h>
 #endif

```

**Comment by XVilka** [comment]
Thanks! We are trying to make it work in this PR: https://github.com/rizinorg/rizin/pull/3995

I am closing this as not a bug, then.
