### PR TITLE
Fix install when run with meson.exe. Closes #3988.

### LINKED ISSUE #3988: `meson install` broken with Windows MSI installer
After having installed meson via the MSI installer, I get this when trying to run `meson install` (or `ninja install`):
```
F:\projects\mesontest\libfoo\buildwin>meson install
Traceback (most recent call last):
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "meson.py", line 29, in <module>
  File "mesonbuild\mesonmain.py", line 379, in main
  File "mesonbuild\mesonmain.py", line 283, in run
  File "mesonbuild\minstall.py", line 23, in <module>
ImportError: cannot import name '__file__'
```
- the problem exists with `meson-0.47.1-32.msi`, also with `meson-0.47.0-32.msi`
- works correctly with `meson-0.46.1-32.msi`
- also works correctly when installing python and getting meson 0.47.1 via `pip3 install meson`

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

File: mesonbuild/minstall.py [hunk 1]
```diff
@@ -20,7 +20,12 @@
 from .scripts import destdir_join
 from .mesonlib import is_windows, Popen_safe
 from .mtest import rebuild_all
-from __main__ import __file__ as main_file
+try:
+    from __main__ import __file__ as main_file
+except ImportError:
+    # Happens when running as meson.exe which is native Windows.
+    # This is only used for pkexec which is not, so this is fine.
```
[the remark this answers is not in the document]
Comment (jpakkane) [reply mesonbuild/minstall.py]: Dunno, but this is only used when pkcon is called and I would imagine most of those people don't use zipapps.

[the remark this answers is not in the document]
Comment (nirbheek) [reply mesonbuild/minstall.py]: Was just wondering if the comment should be amended :)

[the remark this answers is not in the document]
Comment (jpakkane) [reply mesonbuild/minstall.py]: Meh. If the bug ever manifests, the backtrace will be obvious. CI is suffciently backlogged enough as it is.
