### ISSUE TITLE
Cython sanity check uses PKG_CONFIG_PATH while python.find_installation().dependency() does not

### ISSUE THREAD

**Issue by jorisvandenbossche** [mesonbuild/meson#15740]
**Describe the bug**

I noticed that building pandas from source in a conda environment with the latest meson 1.11 stopped working (and downgrading just meson to 1.10 made it work), with a `ERROR: Compiler cython cannot compile programs.` error.

Looking at the logs, it seems that cython is now failing in the sanity check step, because it finds system Python instead of the Python inside the conda environment. 

<details>
<summary>Relevant part of meson-log.txt</summary>

```
Detecting compiler via: `cython -V` -> 0
stdout:
Cython version 3.2.4
-----------
stderr:
Cython version 3.2.4
-----------
Sanity check transpiler command line: cython --fast-fail -o sanity_check_for_cython.c sanity_check_for_cython.pyx -3
Sanity check transpiler stdout:

-----
Sanity check transpiler stderr:

-----
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
Determining dependency 'python3' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --modversion python3` -> 0
stdout:
3.10
-----------
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --cflags python3` -> 0
stdout:
-I/usr/include/python3.10 -I/usr/include/x86_64-linux-gnu/python3.10
-----------
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs python3` -> 0
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs python3` -> 0
Run-time dependency python3 found: YES 3.10
checking compilation of transpiled source:
Sanity check compiler command line: /home/joris/scipy/repos/test-meson-cython/.pixi/envs/default/bin/x86_64-conda-linux-gnu-cc -D_FILE_OFFSET_BITS=64 -o sanity_check_for_cython.so sanity_check_for_cython.c -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/joris/scipy/repos/test-meson-cython/.pixi/envs/default/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/joris/scipy/repos/test-meson-cython/.pixi/envs/default/include -D_FILE_OFFSET_BITS=64 -fPIC -I/usr/include/python3.10 -I/usr/include/x86_64-linux-gnu/python3.10 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/joris/scipy/repos/test-meson-cython/.pixi/envs/default/lib -Wl,-rpath-link,/home/joris/scipy/repos/test-meson-cython/.pixi/envs/default/lib -L/home/joris/scipy/repos/test-meson-cython/.pixi/envs/default/lib -shared -Wl,--allow-shlib-undefined
Sanity check compile stdout:

-----
Sanity check compile stderr:
In file included from /usr/include/python3.10/Python.h:8,
                 from sanity_check_for_cython.c:19:
/usr/include/python3.10/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.10/pyconfig.h: No such file or directory
    3 | #  include <x86_64-linux-gnu/python3.10/pyconfig.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

-----

../meson.build:1:0: ERROR: Compiler cython cannot compile programs.
```

</details>

Things that seem to fix it (but so were not needed for older versions of meson):

- Explicitly setting `PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkgconfig`
- Installing `pkg-config` in the local conda environment

**To Reproduce**

Minimal meson.build file:

```python
project(
  'test-cython',
  ['c', 'cython'],
  version: '0.1.0',
)

py = import('python').find_installation(pure: false)
```

and then running `meson setup . build/` fails with meson 1.11 but works with 1.10, _if_ running this inside a conda env (with the c compiler also getting detected from the conda env)

**Expected behavior**
That this keeps working as with meson 1.10 (i.e. works out of the box in a conda env without having to set env variables manually)

**system parameters**
* Native build
* Ubuntu 22.04
* Python 3.13 (but not limited to this version)
* what `meson --version`: 1.11.1

**Comment by jorisvandenbossche** [comment]
This might be related to https://github.com/mesonbuild/meson/pull/15092 (cc @dcbaker) which replaced the previous light-weight cython check with a more elaborate sanity check.

Also, with the above `meson.build` file, it is quickly reproducible using `pixi`, which can quickly set up conda envs on the fly:

```
$ pixi exec --with meson=1.11.1 --with meson-python --with python=3.13 --with cython --with c-compiler meson setup . build111
The Meson build system
Version: 1.11.1
Source dir: /home/joris/scipy/repos/test-meson-cython
Build dir: /home/joris/scipy/repos/test-meson-cython/build111
Build type: native build
Project name: test-cython
Project version: 0.1.0
C compiler for the host machine: /home/joris/.cache/rattler/cache/cached-envs-v0/meson-f46c55a9fd5ef7c8/bin/x86_64-conda-linux-gnu-cc (gcc 14.3.0 "x86_64-conda-linux-gnu-cc (conda-forge gcc 14.3.0-18) 14.3.0")
C linker for the host machine: /home/joris/.cache/rattler/cache/cached-envs-v0/meson-f46c55a9fd5ef7c8/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.45.1

meson.build:1:0: ERROR: Compiler cython cannot compile programs.
```

vs

```
$ pixi exec --with meson=1.10.0 --with meson-python --with python=3.13 --with cython --with c-compiler meson setup . build110
The Meson build system
Version: 1.10.0
Source dir: /home/joris/scipy/repos/test-meson-cython
Build dir: /home/joris/scipy/repos/test-meson-cython/build110
Build type: native build
Project name: test-cython
Project version: 0.1.0
C compiler for the host machine: /home/joris/.cache/rattler/cache/cached-envs-v0/meson-4e5056ada20d421e/bin/x86_64-conda-linux-gnu-cc (gcc 14.3.0 "x86_64-conda-linux-gnu-cc (conda-forge gcc 14.3.0-18) 14.3.0")
C linker for the host machine: /home/joris/.cache/rattler/cache/cached-envs-v0/meson-4e5056ada20d421e/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.45.1
Cython compiler for the host machine: cython (cython 3.2.4)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/home/joris/.cache/rattler/cache/cached-envs-v0/meson-4e5056ada20d421e/bin/python3.13)
Build targets in project: 0

Found ninja-1.13.2 at /home/joris/.cache/rattler/cache/cached-envs-v0/meson-4e5056ada20d421e/bin/ninja

```

**Comment by dcbaker** [comment]
Yeah, the previous implementation of the "Cython" sanity check was actually the C sanity check (so not actually testing the output of Cython at all), so I'm not surprised that some cases that previously succeeded are now failing. I will look more and see if this is something that can be resolved.

**Comment by dcbaker** [comment]
I'm going to admit I'm confused about how this is working at all, if pkg-config is returning the system headers in the check, isn't it also returning the system headers when you compile the transpiled cython sources in your build. so even if we stubbed out the sanity check it should still fail to build?

**Comment by eli-schwartz** [comment]
```
import('python').find_installation().dependency()
```

is not guaranteed to be the default python3 installed to /usr.

Myself, I'm surprised that the python3 installed to /usr had Python.h but didn't have x86_64-linux-gnu/python3.10/pyconfig.h. Although that's not really the *issue* here.

**Comment by bonzini** [comment]
Can this be closed? Based on https://github.com/pandas-dev/pandas/pull/65228, it seems like the problem was in the image.

**Comment by dcbaker** [comment]
I'm not sure. I guess the question is whether this constitutes a regression that previous our sanity check didn't do anything and the project configured correctly, or whether that is a regression. I tend to think It's an annoying regression, but maybe as a project we think it's fine?

**Comment by bonzini** [comment]
The question is why it failed. The linked pandas bug has this in root cause:

> The CI conda env uses Python 3.11, but PKG_CONFIG_PATH was empty, so pkg-config fell back to system Python 3.12. The latest runner image has /usr/include/python3.12/pyconfig.h referencing a multiarch header (x86_64-linux-gnu/python3.12/pyconfig.h) that doesn't exist.

There are two layers of bugs here, each of which is worth catching:

* The ubuntu-24.04 runner image updated on 2026-04-14 (ubuntu24/20260413.86) has broken system Python 3.12 headers — the multiarch pyconfig.h is missing, causing the meson Cython sanity check to fail with Compiler cython cannot compile programs
* meson wasn't even finding the desired Python 3.11 headers, and having the broken system ones was actually a stroke of luck, because the system headers were newer and not necessarily 3.11-compatible?

Perhaps Meson could improve how Python headers are found, but the new Cython sanity check seems fine? If so, this would be a new feature and not something for 1.11.2.

**Comment by dcbaker** [comment]
I guess the question is: if those bugs are worth fixing for 1.12, should we add a warning for 1.11 that things may be broken and allow the sanity check to be skipped?

**Comment by bonzini** [comment]
My counter question is whether those are bugs at all, and whether the previously-passing test was actually an undesirable false negative.

**Comment by jorisvandenbossche** [comment]
> Based on https://github.com/pandas-dev/pandas/pull/65228, it seems like the problem was in the image.

To be clear, the problem was not with the image as such (claude's analysis was not the full picture), but the update might have uncovered the bug (as you also already analyzed in https://github.com/mesonbuild/meson/issues/15740#issuecomment-4651633952). The reason I reported this is because I got the same error locally in a conda environment (not on a github actions image)

> Perhaps Meson could improve how Python headers are found, but the new Cython sanity check seems fine?

It might be an issue with the order of the checks? Because as far as I can see, Meson does actually find Python just fine, at the time of `import('python').find_installation(pure: false)` (in the logs, it reports the correct python path). But the cython sanity checks happens before that, when python has not yet been found correctly, and at that point it seems to just use some default system python path?

**Comment by bonzini** [comment]
> Meson does actually find Python just fine, at the time of import('python').find_installation(pure: false) (in the logs, it reports the correct python path). But the cython sanity checks happens before that, when python has not yet been found correctly, and at that point it seems to just use some default system python path?

Yeah, there is some complication here. `find_installation` only finds the program; and while `installation.dependency()` and `installation.extension_module()` do use pkg-config, they only do so via `build-details.json` or `sysconfig.get_config_vars()`, not via `PKGCONFIG_PATH`:

```
        if installation.build_config:
            pkg_libdir = installation.build_config.get('c_api.pkgconfig_path')
            pkg_libdir_origin = 'c_api.pkgconfig_path from the Python build config'
        else:
            pkg_libdir = installation.info['variables'].get('LIBPC')
            pkg_libdir_origin = 'LIBPC'
        if pkg_libdir is None:
            # we do not fall back to system directories, since this could lead
            # to using pkg-config of another Python installation, for example
            # we could end up using CPython .pc file for PyPy
            mlog.debug(f'Skipping pkgconfig lookup, {pkg_libdir_origin} is unset')
            self.is_found = False
            return
```

However, the Cython sanity check uses pkg-config simply with `python{version}` and with no extra checks on the pkgconfig path. So this is the root cause. So @dcbaker you're probably right and it's better to downgrade the `EnvironmentException` to a warning?

**Comment by eli-schwartz** [comment]
Or in other words, cython sanity checks seem to be using `dependency('python3')` which does share implementations with the python.find_installation().dependency() factory but the latter provides an overridden name.

**Comment by msimacek** [comment]
We're also running into this problem under GraalPy. GraalPy's pip applies compatibility patches to packages upon installation and in case of Cython, this introduces some GraalPy-specific C symbols that make GraalPy-installed Cython broken under CPython. So the check fails whenever you try to build anything with meson+cython and have system python-devel installed. When pkg-config doesn't find python, the fallback path to `DependencyMethods.SYSTEM` method seems to works fine and all the later phases use the correct python. Could the fix be to pass `'method': DependencyMethods.SYSTEM` in kwargs of `find_external_dependency`?

**Comment by jorisvandenbossche** [comment]
> Could the fix be to pass `'method': DependencyMethods.SYSTEM` in kwargs of `find_external_dependency`?

No idea if that is the correct fix, but at least that fixes it for me (quickly tried that patch, and then it finds the correct Python from the conda environment, and thus the cython sanity checks pass fine)

**Comment by rgommers** [comment]
I ran into this as well when working on a CI job using `pixi`. The problem occurred because I forgot to include `pkg-config` in `pixi.toml`. Installing `pkg-config` is the cleaner workaround to setting `PKG_CONFIG_PATH` I'd say,; currently `pkg-config` is the first thing tried by the sanity check, so it will find the correct `python` install.

***

That said, this is a bug I'd say, and the fix suggested above isn't right (or at a minimum, not complete). This problem may bite any `meson-python` users that use Cython in case the found `python` install is missing headers or some such thing. Even if it doesn't break, the Cython sanity check is testing the wrong `python` install.

What should happen here I believe is that the sanity check should honor the content of the native file that `meson-python` is passing to `meson setup`. It contains:
```ini
[binaries]
python = '/path/to/bin/python3.14'
```
That's the `python` that `cython` will be targeting for a native build (well, in 99.9x% of cases, you can construct artificial edge cases). In case of cross-compilation, there will be a cross file or a `build_details.json` (specified via [`-Dpython.build_config`](https://mesonbuild.com/Builtin-options.html#python-module)). 

In general, the targeted `python` install is the only one guaranteed to have headers, and be a recent enough Python version. Finding the system version could yield an ancient version; even on latest macOS it's Python 3.9 and that's the very lowest version that Cython supports, so this problem may hit more people soon:

https://github.com/cython/cython/blob/ab9899598718f3d949e86aff7d34bdee622ebe72/Cython/Compiler/Main.py#L10-L12

Either the sanity check should guarantee that it yields the same result as `import('python').find_installation().dependency()`, or it should not error. And preferably not even warn, that will still send people on a goose chase to find the cause of the warning.

**Comment by bonzini** [comment]
> `'method': DependencyMethods.SYSTEM`

That would still not match entirely what `python.find_installation().dependency()` does, because that one also uses by default the PKGCONFIG method. The root cause is the missing `installation` argument in the Cython sanity check.

But because one can use Cython with multiple installation, the check cannot be anything more than advisory. I'll create a patch.

**Comment by mkoeppe** [comment]
I was looking at #15092, where the more elaborate Cython sanity checking code was introduced by @dcbaker; is there a more detailed discussion available somewhere that led to the decision to introduce this complexity? (The PR description is rather brief.)

(More specifically, has any non-"sane" Cython been encountered in the wild that this check protects from?)

**Comment by bonzini** [comment]
The PR description does describe the main improvement:

> So in the Vala cases this means that C gets called with the C implementation's code, and then we call it good. 

In other words it was not testing Vala/Cython at all. More in general there was a lot of duplicate code across languages. There were also some bugs that will be fixed in 1.12.1, but for transpilers the main change is actually testing the transpiler.
