### PR TITLE
tests: skip importstd with gcc on Windows

### PR DESCRIPTION
**Pull request by lazka**
It's failing since we updated from gcc 15.2 to 16.1 in MSYS2.

The test was checking for an unreleased 15.3 so the test was never run on Windows to begin with. Just skip it with gcc on Windows.

fyi, it fails with:
undefined reference to 'std::__open_terminal(_iobuf*)'
undefined reference to 'std::__write_to_terminal(void*, std::span<char, 4294967295u>)'

### CODE REVIEW

File: test cases/common/288 importstd/meson.build [hunk 1]
```diff
@@ -5,8 +5,9 @@ cpp = meson.get_compiler('cpp')
 
 cpp_id = cpp.get_id()
 cpp_version = cpp.version()
+is_windows = host_machine.system() == 'windows'
 
-if cpp_id == 'gcc' and cpp_version.version_compare('>=15.3')
+if not is_windows and cpp_id == 'gcc' and cpp_version.version_compare('>=15.3')
```
Comment (eli-schwartz) [inline test cases/common/288 importstd/meson.build:12]: Please update comment to note why we skip on windows.

Comment (lazka) [reply test cases/common/288 importstd/meson.build:12]: Will do

**Review by dcbaker — APPROVED** [review]
