### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'seek'

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#4470]
I happened to still install meson master in pygobject CI, which just broke:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 109, in run
    return options.run_func(options)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 783, in run
    return th.doit()
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 533, in doit
    self.run_tests(tests)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 693, in run_tests
    self.drain_futures(futures)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 708, in drain_futures
    result.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 265, in run
    return self._run_cmd(wrap + cmd + self.test.cmd_args + self.options.test_args)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 374, in _run_cmd
    stdout.seek(0)
AttributeError: 'NoneType' object has no attribute 'seek'
```

**Comment by jpakkane** [comment]
@marcelhollerbach could this be caused by #4449?

**Comment by lazka** [comment]
Thanks @dcbaker

**Comment by marcelhollerbach** [comment]
@jpakkane sorry for the trouble, I was away a few days - thus i did not answer :(
