### PR TITLE
Replace cmd line arguments on install scripts. Closes #1681.

### LINKED ISSUE #1681: @BUILD_ROOT@ and @SOURCE_ROOT@ don't get replaced before running gtk-doc helper
This happens when building gstreamer with gtk-doc enabled.
Running `git bisect` shows it is caused by commit 976c9ab.

```
Running custom install script '/usr/local/bin/python3 /tmp/meson/meson.py --internal gtkdoc --sourcedir=/home/lantw44/gnome/source/gstreamer --builddir=/tmp/gstreamer-build --subdir=docs/gst --headerdirs=/home/lantw44/gnome/source/gstreamer/docs/gst/../../gst --mainfile=gstreamer-docs.sgml --modulename=gstreamer --mode=auto --scanargs=--deprecated-guards=GST_DISABLE_DEPRECATED@@--ignore-decorators=GST_EXPORT@@--ignore-headers=gettext.h glib-compat-private.h glib-compat.h gst-i18n-app.h gst-i18n-lib.h gst_private.h gstelementdetails.h gstmacros.h grammar.tab.h grammar.tab.pre.h math-compat.h types.h --gobjects-types-file=/tmp/gstreamer-build/docs/gst/gstreamer.types --content-files=building.xml@@running.xml@@/tmp/gstreamer-build/docs/version.entities --cflags=-I@BUILD_ROOT@/. -I@SOURCE_ROOT@/. -I/home/lantw44/gnome/devinstall/include/glib-2.0 -I/home/lantw44/gnome/devinstall/lib/glib-2.0/include -pthread --ldflags=-lgstreamer-1.0 -L/tmp/gstreamer-build/gst -Wl,-rpath /tmp/gstreamer-build/gst -L/home/lantw44/gnome/devinstall/lib -lgobject-2.0 -lglib-2.0 -lintl -lgmodule-2.0 -pthread -lm -L/usr/local/lib -lunwind -lexecinfo --cc=clang -pedantic -std=c11 --ld=clang -pedantic -std=c11'
Building documentation for gstreamer

Error in gtkdoc helper script:
'gtkdoc-scangobj' failed with status 1
gstreamer-scan.c:7:10: fatal error: 'gst/gst.h' file not found
#include <gst/gst.h>
         ^
1 error generated.
Traceback (most recent call last):
  File "/home/lantw44/gnome/devinstall/bin/gtkdoc-scangobj", line 69, in <module>
    sys.exit(scangobj.run(options))
  File "/home/lantw44/gnome/devinstall/share/gtk-doc/python/gtkdoc/scangobj.py", line 1255, in run
    res = subprocess.check_call(command, shell=True)
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'clang -pedantic -std=c11 >/dev/null -I@BUILD_ROOT@/. -I@SOURCE_ROOT@/. -I/home/lantw44/gnome/devinstall/include/glib-2.0 -I/home/lantw44/gnome/devinstall/lib/glib-2.0/include -pthread -c -o gstreamer-scan.o gstreamer-scan.c' returned non-zero exit status 1
```

### PR DESCRIPTION
**Pull request by jpakkane**
Not actually tested, please verify that this works. Thanks.

### CODE REVIEW

**Comment by tp-m** [comment]
This fix works for me, thanks! Fails without, builds fine with (gstreamer + gst-plugins-base in gst-build).

I still see quite a few `@@` in places, but it looks those are use as multi-args separators for meson-internal args?

e.g.
```
Running custom install script '/usr/bin/python3 /home/tpm/Devel/meson/meson.py --internal gtkdoc --sourcedir=/home/tpm/Devel/gst-build --builddir=/tmp/bgst --subdir=subprojects/gst-devtools/validate/docs/validate --headerdirs=/home/tpm/Devel/gst-build/subprojects/gst-devtools/validate/docs/validate/../../gst/validate --mainfile=gst-validate-docs.sgml --modulename=gst-validate --mode=auto --scanargs=--deprecated-guards=GST_DISABLE_DEPRECATED@@--ignore-decorators=GST_EXPORT@@--ignore-headers=gettext.h gst-validate-internal.h gst-validate-monitor.h gst-validate-bin-monitor.h gst-validate-element-monitor.h gst-validate-pad-monitor.h gst-validate-override.h gst-validate-override-registry.h gst-validate-utils.h gst-validate-media-info.h  gst-validate-report.h  media-descriptor.h media-descriptor-parser.h media-descriptor-writer.h gst-validate-i18n-lib.h --gobjects-types-file=/tmp/bgst/subprojects/gst-devtools/validate/docs/validate/gst-validate.types --fixxrefargs=--extra-dir=/usr/share/gtk-doc/html/@@--extra-dir=/usr/share/gtk-doc/html/@@--extra-dir=/usr/share/gtk-doc/html/@@--html-dir=/tmp/pgst/share/gtk-doc/html/ --content-files=gst-validate.xml@@gst-validate-transcoding.xml@@gst-validate-media-check.xml@@gst-validate-launcher.xml@@envvariables.xml@@scenarios.xml --cflags=-I/tmp/bgst/subprojects/gst-devtools/validate/. -I/home/tpm/Devel/gst-build/subprojects/gst-devtools/validate/. -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/orc-0.4 -I/usr/include/json-glib-1.0 -I/tmp/bgst/subprojects/gstreamer/. -I/home/tpm/Devel/gst-build/subprojects/gstreamer/. -I/tmp/bgst/subprojects/gst-plugins-base/gst-libs -I/home/tpm/Devel/gst-build/subprojects/gst-plugins-base/gst-libs -I/tmp/bgst/subprojects/gstreamer/libs -I/home/tpm/Devel/gst-build/subprojects/gstreamer/libs --ldflags=-lgstvalidate-1.0 -L/tmp/bgst/subprojects/gst-devtools/validate/gst/validate -Wl,-rpath /tmp/bgst/subprojects/gst-devtools/validate/gst/validate -lglib-2.0 -lgobject-2.0 -lgmodule-2.0 -pthread -lgio-2.0 -lm -lorc-0.4 -ljson-glib-1.0 -lgstreamer-1.0 -L/tmp/bgst/subprojects/gstreamer/gst -Wl,-rpath /tmp/bgst/subprojects/gstreamer/gst -ldl -lunwind -lgstpbutils-1.0 -L/tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/pbutils -Wl,-rpath /tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/pbutils -lgstvideo-1.0 -L/tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/video -Wl,-rpath /tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/video -lgstbase-1.0 -L/tmp/bgst/subprojects/gstreamer/libs/gst/base -Wl,-rpath /tmp/bgst/subprojects/gstreamer/libs/gst/base -lgstaudio-1.0 -L/tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/audio -Wl,-rpath /tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/audio -lgsttag-1.0 -L/tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/tag -Wl,-rpath /tmp/bgst/subprojects/gst-plugins-base/gst-libs/gst/tag --cc=ccache cc --ld=ccache cc'
```
