### PR TITLE
cmake: add libraries from dependencies in the cmake-file-api

### LINKED ISSUE #10984: CMake support ignores dependent libraries
**Describe the bug**
If I load a CMake project as a subproject and that CMake project contains multiple libraries that depend on each other, Meson will only compile one of the libraries and ignore the other one.

```
FAILED: main 
c++  -o main main.p/main.cc.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group subprojects/liba/liblibc.a -Wl,--end-group
/usr/bin/ld: subprojects/liba/liblibc.a.p/libc_src_libc.cc.o: in function `c()':
/home/elias/meson-cmake-test/_build/../subprojects/liba/libc/src/libc.cc:5: undefined reference to `b()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**To Reproduce**
[meson-cmake-test.zip](https://github.com/mesonbuild/meson/files/9924396/meson-cmake-test.zip)
The project contains two main files. One of those is only there to prove that the CMake project works on its own.

**Expected behavior**
I expect the project to build without errors.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
plain native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Arch Linux
* what Python version are you using e.g. 3.8.0
Python 3.10.8
* what `meson --version`
0.63.3
* what `ninja --version` if it's a Ninja build
1.11.1

### PR DESCRIPTION
**Pull request by kiwixz**
Fixes #10984.

CMake doesn't expose any linking flags between static libraries targets, so meson was not aware of those dependencies.

This PR implements the parsing of `dependencies` field in [cmake-file-api](https://cmake.org/cmake/help/v3.14/manual/cmake-file-api.7.html#codemodel-version-2-target-object)'s targets.

Currently, this simply forwards the artifacts of the dependency as additional libs to link if its a static library; but I hope it will be useful to have access to this property for the future cmake-file-api struggles.

### CODE REVIEW

File: mesonbuild/cmake/fileapi.py [hunk 1]
```diff
@@ -257,6 +256,27 @@ def parse_project(pro: T.Dict[str, T.Any]) -> T.Dict[str, T.Any]:
 
             return pro_data
 
+        def find_target(cnf_data: T.Dict[str, T.Any], id: str) -> T.Optional[T.Any]:
```
Comment (tristan957) [inline mesonbuild/cmake/fileapi.py:259]: I think the convention is to use a leading underscore for private functions in Meson. Also, it looks like you need to to mark these as `@staticmethod`? You aren't taking `self` or `cls`

Comment (eli-schwartz) [reply mesonbuild/cmake/fileapi.py:259]: Well, everything is a private method already. :P 

Narrower input types would also be great if possible, although I think that would be ultimately an improvement on some existing code. What does CMakeConfigurations contain? Well, currently only created by parse_project...

`T.Optional[T.Any]` is an odd-looking annotation, since Any includes Optional. I *think* it always has to be a dict compatible with tgt_data?

Comment (kiwixz) [reply mesonbuild/cmake/fileapi.py:259]: Alright, I looked into it and there are basically 3 solutions:
1. Remove the dicts and directly use the final classes from common.py (`CMakeConfiguration`, `CMakeProject`, `CMakeTarget`).  Would be great, and not just for typing, but that's a lot of refactoring!
2. Add TypedDict, its a bit less effort but it would be a waste if *1.* is the proper solution
3. Keep a consistent way of describing the root dict like the other functions in the file; not great for typing but serves more as a kind of documentation

I'll push the latter for now, I hope it will be enough for this PR.

**Comment by tristan957** [comment]
Test failure is relevant

File: mesonbuild/cmake/fileapi.py (hunk 1 above)
Comment (tristan957) [reply mesonbuild/cmake/fileapi.py]: Cool. Let's aim for 1 in the future if you feel inclined to do that. Refactors that add typing and increase code clarity make subsequent review much nicer

**Comment by kiwixz** [comment]
Seems fixed!

**Comment by tristan957** [comment]
@Volker-Weissmann any chance you are familiar with this API and want to provide a review?

File: mesonbuild/cmake/fileapi.py [hunk 2]
```diff
@@ -257,6 +256,27 @@ def parse_project(pro: T.Dict[str, T.Any]) -> T.Dict[str, T.Any]:
 
             return pro_data
 
+        def find_target(cnf_data: T.Dict[str, T.Any], id: str) -> T.Optional[T.Dict[str, T.Any]]:
```
Comment (tristan957) [inline mesonbuild/cmake/fileapi.py:259]: Since these functions aren't exported, I would prefix them with an underscore

Comment (kiwixz) [reply mesonbuild/cmake/fileapi.py]: done!

Comment (tristan957) [reply mesonbuild/cmake/fileapi.py]: Perfect

**Comment by tristan957** [comment]
@xclaesse do you think you could take a look at this? Pretty small PR and comes with a test :). I know this isn't your forte, but since @mensinda isn't available these days, we need CMake help, which @kiwixz has provided through a few great PRs.

File: mesonbuild/cmake/fileapi.py (hunk 2 above)
Comment (eli-schwartz) [reply mesonbuild/cmake/fileapi.py]: NACK, please revert. It's an unnecessary change and the point of underscores is to mark private-but-exported functions as "should not be used" and "is not imported by star imports".

Functions defined inside of other functions get unbound when the function completes and do not need underscores.

Comment (tristan957) [reply mesonbuild/cmake/fileapi.py]: My bad, I saw this indented, and didn't see it was just within a function.

Comment (kiwixz) [reply mesonbuild/cmake/fileapi.py:259]: No problem, reverted!

Comment (eli-schwartz) [reply mesonbuild/cmake/fileapi.py:259]: It can be confusing to spot the difference, my trick is to check whether the first argument is `self` -- functions that are aligned at the start of the line are usually module functions, and functions that take `self` are usually class methods, functions that do neither one are usually temporary functions.

**Comment by Volker-Weissmann** [comment]
> @Volker-Weissmann any chance you are familiar with this API and want to provide a review?

Long story short: I thought that this PR creates bugs for certain cmake packages and spend 2 days trying to confirm that. In the end, I could not find such a case.

**Comment by tristan957** [comment]
@eli-schwartz are you comfortable merging this?
