### ISSUE TITLE
Meson rewrite fails with unhandled exception

### ISSUE THREAD

**Issue by Finii** [mesonbuild/meson#14382]
**Describe the bug**

`meson rewrite` crashed with stacktrace:

```
Analyzing meson file: ./meson.build
Traceback (most recent call last):
  File "/home/ujastrow/git/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "/home/ujastrow/git/meson/mesonbuild/rewriter.py", line 1074, in run
    raise e
  File "/home/ujastrow/git/meson/mesonbuild/rewriter.py", line 1054, in run
    rewriter.analyze_meson()
  File "/home/ujastrow/git/meson/mesonbuild/rewriter.py", line 374, in analyze_meson
    self.interpreter.analyze()
  File "/home/ujastrow/git/meson/mesonbuild/ast/introspection.py", line 360, in analyze
    self.parse_project()
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 138, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 203, in evaluate_codeblock
    raise e
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 209, in evaluate_statement
    return self.function_call(cur)
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 536, in function_call
    res = func(node, func_args, kwargs)
  File "/home/ujastrow/git/meson/mesonbuild/ast/introspection.py", line 122, in func_project
    self.coredata.set_default_options(self.default_options, self.subproject, self.environment)
  File "/home/ujastrow/git/meson/mesonbuild/coredata.py", line 650, in set_default_options
    self.set_options(options, subproject=subproject, first_invocation=env.first_invocation)
  File "/home/ujastrow/git/meson/mesonbuild/coredata.py", line 573, in set_options
    val = options.BUILTIN_OPTIONS[key].prefixed_default(key, prefix)
AttributeError: 'UserStringOption' object has no attribute 'prefixed_default'

meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**

Have `meson.build`:

```
project('lalala', 'cpp',
    default_options : [
        'prefix=/export/doocs',
    ],
)
```

Run

```
meson rewrite -V kwargs info project /
```

Print project information, not crash

**system parameters**

* Ubuntu 20.04
* Python 3.8.10
* meson 1.7.99 (1.7.0-204-gd17df82ef)

----

`git bisect` puts the blame on

```
d37d649b08b832d52fa684bc0506829fb40d5261 is the first bad commit
commit d37d649b08b832d52fa684bc0506829fb40d5261
Author: Jussi Pakkanen <jpakkane@gmail.com>
Date:   Sun Apr 14 12:58:30 2024 +0300

    Make all Meson level options overridable per subproject.
```

**Comment by Finii** [comment]
The actual reason for the crash varies, for HEAD it is as shown above, further down bisecting it gets (shown below).

`no attribute 'sanitize_prefix'`

Possibly that had been fixed with the fix for
* #14329 

But now we have the `no attribute 'prefixed_default'`.

```
$ meson rewrite -V kwargs info project /
Analyzing meson file: ./meson.build
Traceback (most recent call last):
  File "/home/ujastrow/git/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "/home/ujastrow/git/meson/mesonbuild/rewriter.py", line 1074, in run
    raise e
  File "/home/ujastrow/git/meson/mesonbuild/rewriter.py", line 1054, in run
    rewriter.analyze_meson()
  File "/home/ujastrow/git/meson/mesonbuild/rewriter.py", line 374, in analyze_meson
    self.interpreter.analyze()
  File "/home/ujastrow/git/meson/mesonbuild/ast/introspection.py", line 372, in analyze
    self.parse_project()
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 129, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/home/ujastrow/git/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/home/ujastrow/git/meson/mesonbuild/ast/introspection.py", line 134, in func_project
    self.coredata.set_default_options(self.default_options, self.subproject, self.environment)
  File "/home/ujastrow/git/meson/mesonbuild/coredata.py", line 716, in set_default_options
    self.set_options(options, subproject=subproject, first_invocation=env.first_invocation)
  File "/home/ujastrow/git/meson/mesonbuild/coredata.py", line 587, in set_options
    prefix = self.sanitize_prefix(opts_to_set[pfk])
AttributeError: 'CoreData' object has no attribute 'sanitize_prefix'

meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by bonzini** [comment]
@dcbaker, any news?

**Comment by dcbaker** [comment]
I have patches, I'm peeling them out of a much larger branch of reworks following the optionrefactor changes, I'll try to get them out later today.
