### ISSUE TITLE
0.52.1 regression on Alpine Linux

### ISSUE THREAD

**Issue by rilian-la-te** [mesonbuild/meson#6277]
**Describe the bug**
vala-panel does not build with meson on alpine container
```
$ meson bld --prefix=/usr && cd bld
The Meson build system
Version: 0.52.1
Source dir: /builds/vala-panel-project/vala-panel
Build dir: /builds/vala-panel-project/vala-panel/bld
Build type: native build
Project name: vala-panel
Project version: 0.5.0
C compiler for the host machine: cc (gcc 9.2.0 "cc (Alpine 9.2.0) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.33.1
Vala compiler for the host machine: valac (valac 0.46.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency glib-2.0 found: YES 2.62.3
Run-time dependency gio-2.0 found: YES 2.62.3
Run-time dependency gio-unix-2.0 found: YES 2.62.3
Run-time dependency gmodule-2.0 found: YES 2.62.3
Run-time dependency gtk+-3.0 found: YES 3.24.13
Library m found: YES
Configuring config.h using configuration
Configuring default using configuration
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Library vala-panel found: YES
Run-time dependency libwnck-3.0 found: YES 3.32.0
Run-time dependency gdk-x11-3.0 found: YES 3.24.13
Library posix found: YES
WARNING: Project targetting '>=0.49.0' but tried to use feature introduced in '0.51.0': args arg in i18n.merge_file
Build targets in project: 55
WARNING: Project specifies a minimum meson_version '>=0.49.0' but uses features which were added in newer versions:
 * 0.51.0: {'args arg in i18n.merge_file'}
Found ninja-1.9.0 at /usr/bin/ninja
$ ninja dist
[0/1] Creating source packages
Cloning into '/builds/vala-panel-project/vala-panel/bld/meson-dist/vala-panel-0.5.0'...
done.
Note: switching to '6479889576a3e48303f92b2fb621f3e6badbca24'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Submodule 'cmake' (https://gitlab.com/vala-panel-project/cmake-vala.git) registered for path 'cmake'
Cloning into '/builds/vala-panel-project/vala-panel/bld/meson-dist/vala-panel-0.5.0/cmake'...
Submodule path 'cmake': checked out 'a156743ddd3b4af6bc7efe0077fdd4d2f8db8ab0'
The Meson build system
Version: 0.52.1
Source dir: /builds/vala-panel-project/vala-panel/bld/meson-private/dist-unpack/vala-panel-0.5.0
Build dir: /builds/vala-panel-project/vala-panel/bld/meson-private/dist-build
Build type: native build
WARNING: Unknown options: "c_args, c_link_args, c_std, vala_args, vala_link_args"
Project name: vala-panel
Project version: 0.5.0
C compiler for the host machine: cc (gcc 9.2.0 "cc (Alpine 9.2.0) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.33.1
Vala compiler for the host machine: valac (valac 0.46.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency glib-2.0 found: YES 2.62.3
Run-time dependency gio-2.0 found: YES 2.62.3
Run-time dependency gio-unix-2.0 found: YES 2.62.3
Run-time dependency gmodule-2.0 found: YES 2.62.3
Run-time dependency gtk+-3.0 found: YES 3.24.13
Library m found: YES
Configuring config.h using configuration
Configuring default using configuration
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Library vala-panel found: YES
Run-time dependency libwnck-3.0 found: YES 3.32.0
Run-time dependency gdk-x11-3.0 found: YES 3.24.13
Library posix found: YES
WARNING: Project targetting '>=0.49.0' but tried to use feature introduced in '0.51.0': args arg in i18n.merge_file
Build targets in project: 55
WARNING: Project specifies a minimum meson_version '>=0.49.0' but uses features which were added in newer versions:
 * 0.51.0: {'args arg in i18n.merge_file'}
Found ninja-1.9.0 at /usr/bin/ninja
[1/122] Generating version.h with a custom command.
[2/122] Generating org.valapanel.application.desktop_data_merge with a custom command.
[3/122] Compiling C object 'util/9342af2@@util@sta/boxed-wrapper.c.o'.
[4/122] Generating org.valapanel.application.appdata.xml_data_merge with a custom command.
[5/122] Compiling C object 'util/9342af2@@util@sta/glistmodel-filter.c.o'.
[6/122] Compiling C object 'util/9342af2@@util@sta/misc.c.o'.
[7/122] Linking static target util/libutil.a.
[8/122] Generating runner_c with a custom command.
[9/122] Generating runner_h with a custom command.
[10/122] Generating vala-panel-util-enums.h with a meson_exe.py custom command.
[11/122] Compiling C object 'runner/527aa9f@@vala-panel-runner@exe/info-data.c.o'.
[12/122] Generating vala-panel-util-enums.c with a meson_exe.py custom command.
[13/122] Compiling C object 'util/gtk/8b535df@@util-gtk@sta/generic-config-dialog.c.o'.
[14/122] Compiling C object 'util/gtk/8b535df@@util-gtk@sta/meson-generated_.._vala-panel-util-enums.c.o'.
[15/122] Compiling C object 'util/gtk/8b535df@@util-gtk@sta/menu-maker.c.o'.
[16/122] Compiling C object 'util/gtk/8b535df@@util-gtk@sta/misc-gtk.c.o'.
[17/122] Compiling C object 'util/gtk/8b535df@@util-gtk@sta/css.c.o'.
[18/122] Compiling C object 'util/gtk/8b535df@@util-gtk@sta/launcher-gtk.c.o'.
[19/122] Linking static target util/gtk/libutil-gtk.a.
[20/122] Compiling C object 'runner/527aa9f@@vala-panel-runner@exe/runner-app.c.o'.
[21/122] Compiling C object 'runner/527aa9f@@vala-panel-runner@exe/meson-generated_.._runner.c.o'.
[22/122] Compiling C object 'runner/527aa9f@@vala-panel-runner@exe/runner.c.o'.
[23/122] Linking target runner/vala-panel-runner.
FAILED: runner/vala-panel-runner 
cc  -o runner/vala-panel-runner 'runner/527aa9f@@vala-panel-runner@exe/meson-generated_.._runner.c.o' 'runner/527aa9f@@vala-panel-runner@exe/runner.c.o' 'runner/527aa9f@@vala-panel-runner@exe/info-data.c.o' 'runner/527aa9f@@vala-panel-runner@exe/runner-app.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--whole-archive -Wl,--start-group util/gtk/libutil-gtk.a util/libutil.a -Wl,--no-whole-archive /usr/lib/libgio-2.0.so /usr/lib/libgobject-2.0.so /usr/lib/libglib-2.0.so /usr/lib/libintl.so -Wl,--export-dynamic /usr/lib/libgmodule-2.0.so -pthread /usr/lib/libgtk-3.so /usr/lib/libgdk-3.so /usr/lib/libpangocairo-1.0.so /usr/lib/libpango-1.0.so /usr/lib/libharfbuzz.so /usr/lib/libatk-1.0.so /usr/lib/libcairo-gobject.so /usr/lib/libcairo.so /usr/lib/libgdk_pixbuf-2.0.so -lm -Wl,--end-group
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(boxed-wrapper.c.o): in function `boxed_wrapper_get_type':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:28: multiple definition of `boxed_wrapper_get_type'; util/gtk/libutil-gtk.a(boxed-wrapper.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:28: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(boxed-wrapper.c.o): in function `boxed_wrapper_new':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:50: multiple definition of `boxed_wrapper_new'; util/gtk/libutil-gtk.a(boxed-wrapper.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:50: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(boxed-wrapper.c.o): in function `boxed_wrapper_get_boxed':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:58: multiple definition of `boxed_wrapper_get_boxed'; util/gtk/libutil-gtk.a(boxed-wrapper.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:58: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(boxed-wrapper.c.o): in function `boxed_wrapper_set_boxed':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:62: multiple definition of `boxed_wrapper_set_boxed'; util/gtk/libutil-gtk.a(boxed-wrapper.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:62: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(boxed-wrapper.c.o): in function `boxed_wrapper_dup_boxed':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:70: multiple definition of `boxed_wrapper_dup_boxed'; util/gtk/libutil-gtk.a(boxed-wrapper.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/boxed-wrapper.c:70: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(glistmodel-filter.c.o): in function `vala_panel_list_model_filter_get_type':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:46: multiple definition of `vala_panel_list_model_filter_get_type'; util/gtk/libutil-gtk.a(glistmodel-filter.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:46: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(glistmodel-filter.c.o): in function `vala_panel_list_model_filter_set_max_results':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:184: multiple definition of `vala_panel_list_model_filter_set_max_results'; util/gtk/libutil-gtk.a(glistmodel-filter.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:184: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(glistmodel-filter.c.o): in function `vala_panel_list_model_filter_set_filter_func':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:193: multiple definition of `vala_panel_list_model_filter_set_filter_func'; util/gtk/libutil-gtk.a(glistmodel-filter.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:193: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(glistmodel-filter.c.o): in function `vala_panel_list_model_filter_invalidate':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:206: multiple definition of `vala_panel_list_model_filter_invalidate'; util/gtk/libutil-gtk.a(glistmodel-filter.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:206: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(glistmodel-filter.c.o): in function `vala_panel_list_model_filter_new':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:220: multiple definition of `vala_panel_list_model_filter_new'; util/gtk/libutil-gtk.a(glistmodel-filter.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:220: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(glistmodel-filter.c.o): in function `vala_panel_list_model_filter_new_with_objects':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:230: multiple definition of `vala_panel_list_model_filter_new_with_objects'; util/gtk/libutil-gtk.a(glistmodel-filter.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/glistmodel-filter.c:230: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `child_spawn_func':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:30: multiple definition of `child_spawn_func'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:30: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `vala_panel_launch_with_context':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:35: multiple definition of `vala_panel_launch_with_context'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:35: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `vala_panel_get_default_for_uri':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:54: multiple definition of `vala_panel_get_default_for_uri'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:54: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `vala_panel_add_prop_as_action':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:72: multiple definition of `vala_panel_add_prop_as_action'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:72: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `vala_panel_add_gsettings_as_action':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:79: multiple definition of `vala_panel_add_gsettings_as_action'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:79: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `vala_panel_reset_schema':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:91: multiple definition of `vala_panel_reset_schema'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:91: first defined here
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: util/libutil.a(misc.c.o): in function `vala_panel_reset_schema_with_children':
/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:100: multiple definition of `vala_panel_reset_schema_with_children'; util/gtk/libutil-gtk.a(misc.c.o):/builds/vala-panel-project/vala-panel/bld/meson-private/dist-build/../dist-unpack/vala-panel-0.5.0/util/misc.c:100: first defined here
collect2: error: ld returned 1 exit status
[24/122] Generating vala-panel-enums.h with a meson_exe.py custom command.
ninja: build stopped: subcommand failed.
Testing distribution package /builds/vala-panel-project/vala-panel/bld/meson-dist/vala-panel-0.5.0.tar.xz
Compiling the distribution package failed
FAILED: meson-dist 
/usr/bin/meson dist
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Try to make ninja dist in Alpine Linux with https://gitlab.com/vala-panel-project/vala-panel

**Expected behavior**
As in Arch Linux and Ubuntu Linux, dist should work. Also it was working on Meson 0.51.2

**system parameters**
* Native build
* Alpine Edge container
* Python 3.8.0-r0
* meson 0.52.1-r0
* ninja 1.9.0-r3

**Link to logs**
Failed: https://gitlab.com/vala-panel-project/vala-panel/-/jobs/367742817
Success: https://gitlab.com/vala-panel-project/vala-panel/-/jobs/298621247

**Comment by rilian-la-te** [comment]
@scivision It is C, not vala. It is static library related (static 1 link_whole with static 2, then static 2 links with executable which uses functions from both static - error)

**Comment by eli-schwartz** [comment]
This was fixed by https://gitlab.com/vala-panel-project/vala-panel/-/commit/0ecd5af395c239d6676baa01263b5460f988ad7b

https://mesonbuild.com/Release-notes-for-0-52-0.html#improved-support-for-static-libraries

It was always just fallout from #5936 making static libraries better, and causing some workarounds for a meson bug to trigger different bugs.
