### ISSUE TITLE
mesonintrospect --dependencies no longer works in 0.41.0

### ISSUE THREAD

**Issue by martin-ejdestig** [mesonbuild/meson#1963]
```
Traceback (most recent call last):
  File "/usr/bin/mesonintrospect", line 20, in <module>
    sys.exit(mintro.run(sys.argv[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 245, in run
    list_deps(coredata)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 162, in list_deps
    if d.found():
AttributeError: 'tuple' object has no attribute 'found'
```
Broke with 8cf29bd288cb67008a42a5c9503042f975c04a43 in which CoreData.deps was changed to an OrderedDict?
