### PR TITLE
ExecutableSerialisation: capture and feed are optional strings

### PR DESCRIPTION
**Pull request by xclaesse**
capture is the optional filename stdout is redirected to. feed is the optional filename stdin reads from.

### CODE REVIEW

**Comment by xclaesse** [comment]
I'm working on a much bigger refactoring of handling commands, this is just a few easy commits to get started.

File: test cases/common/152 index customtarget/meson.build [hunk 1]
```diff
@@ -56,6 +56,13 @@ custom_target(
   input: gen[0],
   output: 'foo',
   command: [find_program('check_args.py'), '@INPUT@'],
+  build_by_default: true,
+)
+
+custom_target(
+  output: 'foo2',
+  command: [find_program('check_args.py'), gen[0]],
+  build_by_default: true,
```
Comment (tristan957) [inline test cases/common/152 index customtarget/meson.build:65]: This changes are cause this failure: https://dev.azure.com/jussi0947/jussi/_build/results?buildId=18382&view=logs&j=447df341-d5a1-5d0e-9651-c9f66402368a&t=12f22127-2cd1-5ea8-0ccb-9ba120a59cea&l=2940

File: docs/yaml/builtins/meson.yaml [hunk 2]
```diff
@@ -99,6 +99,8 @@ methods:
           [[custom_target]], as well as strings are accepted.
 
           *(since 0.57.0)* [[@file]] objects and the output of [[configure_file]] may be used.
+          *(since 1.3.0)* [[@custom_tgt]] and [[@custom_idx]] objects may be used as first argument.
```
Comment (tristan957) [inline docs/yaml/builtins/meson.yaml:102]: throw a `the` before `first`

**Review by tristan957 — COMMENTED** [review]
Looks pretty good to me after fixing test failure

File: mesonbuild/backend/backends.py [hunk 3]
```diff
@@ -638,9 +638,9 @@ def as_meson_exe_cmdline(self, exe: T.Union[str, mesonlib.File, build.BuildTarge
                 return es.cmd_args, ''
             args: T.List[str] = []
             if capture:
-                args += ['--capture', str(capture)]
+                args += ['--capture', capture]
             if feed:
-                args += ['--feed', str(feed)]
+                args += ['--feed', feed]
```
Comment (eli-schwartz) [inline mesonbuild/backend/backends.py:643]: When you think about it, this is terrifying. The type annotations say it's a bool, so we cast it to string in the event that it's a literal True? Weird.

This got introduced in f6f35aa906c8ebac21af07c17449df65d08aeaeb with a lot of other code, but probably it was a confusion based on CustomTarget taking capture as a boolean and creating an ExecutableSerialisation as `capture=ofilenames[0] if target.capture else None`. Nice...

File: test cases/common/152 index customtarget/meson.build (hunk 1 above)
Comment (xclaesse) [reply test cases/common/152 index customtarget/meson.build:65]: Oh god, digging that one I found yet another inconsistency: when using `@INPUT@`, `gen[0]` is passed as path relative to builddir. But when passing `gen[0]` directly on the command kwarg, it's passed as absolute path. That test was supposed to catch that but since it didn,t have `build_by_default: true,` it never actually tested it...

File: mesonbuild/backend/backends.py (hunk 3 above)
Comment (eli-schwartz) [reply mesonbuild/backend/backends.py:643]: I've been working on the backend off and on, there's still almost 400 errors in ninjabackend.py. Three of them are:

> mesonbuild/backend/ninjabackend.py:1170:57: error: Argument "capture" to "as_meson_exe_cmdline" of "Backend" has incompatible type "str"; expected "bool | None"  [arg-type]
> mesonbuild/backend/ninjabackend.py:1171:54: error: Argument "feed" to "as_meson_exe_cmdline" of "Backend" has incompatible type "str"; expected "bool | None"  [arg-type]
> -mesonbuild/backend/ninjabackend.py:2654:65: error: Argument "capture" to "as_meson_exe_cmdline" of "Backend" has incompatible type "str"; expected "bool | None"  [arg-type]

This change fixes those.

Comment (eli-schwartz) [reply mesonbuild/backend/backends.py:643]: Merged via 28e6d2be9621dcd1056d6e386576510fd9cd8860, will take a look at the rest later...

File: docs/yaml/builtins/meson.yaml (hunk 2 above)
Comment (xclaesse) [reply docs/yaml/builtins/meson.yaml]: done

**Review by tristan957 — APPROVED** [review]

File: mesonbuild/interpreter/interpreter.py [hunk 4]
```diff
@@ -2685,7 +2685,7 @@ def func_configure_file(self, node: mparser.BaseNode, args: T.List[TYPE_var],
             mlog.log('Configuring', mlog.bold(output), 'with command')
             res = self.run_command_impl(cmd,
                                         {'capture': True, 'check': True, 'env': EnvironmentVariables()},
-                                        True)
+                                        in_builddir=True)
```
Comment (eli-schwartz) [inline mesonbuild/interpreter/interpreter.py:2688]: Is there a particular reason that passing this (non-ambiguous) argument as a kwarg is advantageous? I don't understand what difference this is supposed to make.

File: mesonbuild/interpreter/interpreter.py [hunk 5]
```diff
@@ -758,26 +758,24 @@ def validate_arguments(self, args, argcount, arg_types):
     # better error messages when overridden
     @typed_pos_args(
         'run_command',
-        (build.Executable, ExternalProgram, compilers.Compiler, mesonlib.File, str),
-        varargs=(build.Executable, ExternalProgram, compilers.Compiler, mesonlib.File, str))
+        varargs=(build.Executable, ExternalProgram, compilers.Compiler, mesonlib.File, str),
+        min_varargs=1)
```
Comment (eli-schwartz) [inline mesonbuild/interpreter/interpreter.py:762]: Getting rid of this pointless parsing complexity makes sense, yeah.

File: mesonbuild/interpreter/interpreter.py (hunk 4 above)
Comment (xclaesse) [reply mesonbuild/interpreter/interpreter.py:2688]: Just a small pet peeve of mine, when passing just "true" you have to check signature to know what it means.

Comment (eli-schwartz) [reply mesonbuild/interpreter/interpreter.py:2688]: Do you plan to change the entire codebase like this? My text editor shows function signatures anyway :D

Comment (xclaesse) [reply mesonbuild/interpreter/interpreter.py:2688]: I can drop that commit if you want, not really important.
