### ISSUE TITLE
Regression: Unable to build project that includes autogenerated headers

### ISSUE THREAD

**Issue by alistair23** [mesonbuild/meson#7800]
**Describe the bug**
When trying to build [OpenTitan](https://github.com/lowrisc/opentitan) there is a regression in meson between versions 0.54 and 0.55.

Using meson 0.54 I am able to build the project.

Using meson 0.55 I see the following error when building:

```shell
[81/563] Compiling C object sw/device/lib/dif/libsw_lib_dif_usbdev.a.p/dif_usbdev.c.o
FAILED: sw/device/lib/dif/libsw_lib_dif_usbdev.a.p/dif_usbdev.c.o 
/usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/riscv32-oe-elf/riscv32-oe-elf-gcc -I/usr/local/oecore-x86_64/./sysroots/riscv32-oe-elf/usr/include -I/scratch/alistair/software/tier2/opentitan -I/scratch/alistair/software/tier2/opentitan/build-out -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -g -nostdinc -isystem/scratch/alistair/software/tier2/opentitan/sw/device/lib/base/freestanding -Os -fvisibility=hidden -Wa,--no-pad-sections -mabi=ilp32 -march=rv32imc -mcmodel=medany --sysroot=/usr/local/oecore-x86_64/sysroots/riscv32-oe-elf -MD -MQ sw/device/lib/dif/libsw_lib_dif_usbdev.a.p/dif_usbdev.c.o -MF 'sw/device/lib/dif/libsw_lib_dif_usbdev.a.p/dif_usbdev.c.o.d' -o sw/device/lib/dif/libsw_lib_dif_usbdev.a.p/dif_usbdev.c.o -c ../sw/device/lib/dif/dif_usbdev.c
../sw/device/lib/dif/dif_usbdev.c:9:10: fatal error: usbdev_regs.h: No such file or directory
    9 | #include "usbdev_regs.h"  // Generated.
```

The `usbdev_regs.h` file is auto generated during the build, and does exist.

It exists in these places when the failure occurs:

```shell
./build-out/sw/device/lib/dif/libsw_lib_dif_usbdev.a.p/usbdev_regs.h
./build-out/sw/device/lib/libusb_ot.a.p/usbdev_regs.h
./build-out/sw/device/examples/hello_usbdev/hello_usbdev_sim_verilator.elf.p/usbdev_regs.h
./build-out/sw/device/examples/hello_usbdev/hello_usbdev_sim_dv.elf.p/usbdev_regs.h
```

The interesting part of the `meson.build` file looks like:

```meson
# USBDEV DIF library (dif_usbdev)
sw_lib_dif_usbdev = declare_dependency(
  link_with: static_library(
    'sw_lib_dif_usbdev',
    sources: [
      hw_ip_usbdev_reg_h,
      'dif_usbdev.c',
    ],
    dependencies: [
      sw_lib_mmio,
      sw_lib_bitfield,
    ],
  )
)
```

I have bisected the regression to commit: b4b1a2c5a145c1459fc4563a289e164e23bd6a02, which is from this PR: https://github.com/mesonbuild/meson/pull/6944

**To Reproduce**
Clone the OpenTitan repo and try to build it:
```shell
git clone https://github.com/lowRISC/opentitan.git
./meson_init.sh ; ninja -C build-out
```

**Expected behavior**
The expectation is that the build will complete with no errors. Using meson 0.54 this is the case.

This is what the log with 0.54 looks like

```shell
ninja: Entering directory `build-out'
[67/563] Generating 'sw/device/lib/dif/5fb29ed@@sw_lib_dif_usbdev@sta/usbdev_regs.h'.
WARNING: Non-homogeneous multireg configin skip multireg specific data generation.
[72/563] Generating 'sw/device/lib/e287d45@@aes_ot@sta/aes_regs.h'.
/scratch/alistair/software/tier2/opentitan/util/reggen/gen_cheader.py:177: UserWarning: Cannot generate a module define of type bit
  warnings.warn(
/scratch/alistair/software/tier2/opentitan/util/reggen/gen_cheader.py:177: UserWarning: Cannot generate a module define of type aes_pkg::sbox_impl_e
  warnings.warn(
/scratch/alistair/software/tier2/opentitan/util/reggen/gen_cheader.py:177: UserWarning: Cannot generate a module define of type int unsigned
  warnings.warn(
/scratch/alistair/software/tier2/opentitan/util/reggen/gen_cheader.py:177: UserWarning: Cannot generate a module define of type logic [aes_reg_pkg::NumAlerts-1:0]
  warnings.warn(
[76/563] Generating 'sw/device/lib/dif/5fb29ed@@sw_lib_dif_alert_handler@sta/alert_handler_regs.h'.
WARNING: ALERT_HANDLER contains extra key hier_path
/scratch/alistair/software/tier2/opentitan/util/reggen/gen_cheader.py:177: UserWarning: Cannot generate a module define of type logic [NAlerts-1:0]
  warnings.warn(
[77/563] Generating 'sw/device/lib/e287d45@@pinmux_ot@sta/pinmux_regs.h'.
WARNING: Non-homogeneous multireg WKUP_DETECTOR skip multireg specific data generation.
[80/563] Generating 'sw/device/lib/e287d45@@flash_ctrl_ot@sta/flash_ctrl_regs.h'.
WARNING: Non-homogeneous multireg MP_REGION_CFG skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK0_INFO0_PAGE_CFG skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK0_INFO1_PAGE_CFG skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK1_INFO0_PAGE_CFG skip multireg specific data generation.
WARNING: Non-homogeneous multireg BANK1_INFO1_PAGE_CFG skip multireg specific data generation.
[85/563] Generating 'sw/device/lib/e287d45@@usb_ot@sta/usbdev_regs.h'.
WARNING: Non-homogeneous multireg configin skip multireg specific data generation.
[109/563] Generating 'sw/device/examples/hello_usbdev/3468fca@@hello_usbdev_sim_dv@exe/usbdev_regs.h'.
WARNING: Non-homogeneous multireg configin skip multireg specific data generation.
[110/563] Generating 'sw/device/examples/hello_usbdev/3468fca@@hello_usbdev_sim_verilator@exe/usbdev_regs.h'.
WARNING: Non-homogeneous multireg configin skip multireg specific data generation.
[181/563] Generating 'sw/device/examples/hello_usbdev/3468fca@@hello_usbdev_fpga_nexysvideo@exe/usbdev_regs.h'.
WARNING: Non-homogeneous multireg configin skip multireg specific data generation.
[563/563] Linking target sw/device/tests/dif/dif_otbn_unittest
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

Yes, this is cross compiling for RISC-V.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Arch

* what Python version are you using e.g. 3.8.0

Python 3.8.5

* what `meson --version`

0.55+

* what `ninja --version` if it's a Ninja build

1.10.1

**Comment by jpakkane** [comment]
If you apply the suspected patch in reverse to the failing version, does it fix it?

**Comment by jpakkane** [comment]
The bug is that it does not generate the -I flag for the private dir. But I can't understand why not and trying to replicate this locally did not work.

Regardless, your generator definition is a bit unoptimal:

```
gen_hw_hdr = generator(
  prog_python,
  output: '@BASENAME@_regs.h',
  arguments: [
    '@SOURCE_DIR@/util/regtool.py', '-D', '-o', '@BUILD_DIR@/@BASENAME@_regs.h',
    '@INPUT@',
  ],
)
```

There is no need to duplicate the name generation in that. Just do:

```
gen_hw_hdr = generator(
  prog_python,
  output: '@BASENAME@_regs.h',
  arguments: [
    '@SOURCE_DIR@/util/regtool.py', '-D', '-o', '@OUTPUT@',
    '@INPUT@',
  ],
)
```

**Comment by alistair23** [comment]
I just checked and this diff fixes the regression when applied to master:

```diff
diff --git a/mesonbuild/backend/backends.py b/mesonbuild/backend/backends.py
index a322d5f16..a325fcddc 100644
--- a/mesonbuild/backend/backends.py
+++ b/mesonbuild/backend/backends.py
@@ -271,7 +271,7 @@ class Backend:
         return self.build_to_src
 
     def get_target_private_dir(self, target):
-        return os.path.join(self.get_target_filename(target, warn_multi_output=False) + '.p')
+        return os.path.join(self.get_target_dir(target), target.get_id())
 
     def get_target_private_dir_abs(self, target):
         return os.path.join(self.environment.get_build_dir(), self.get_target_private_dir(target))
```

**Comment by alistair23** [comment]
Any updates on this? It would be great to have this fixed

**Comment by eli-schwartz** [comment]
@jpakkane said he couldn't reproduce it.

Maybe it would help if you could distill a minimal test case that reproduces the problem? " Clone the *giant repo with specific cross compiler I don't have in a dir I didn't install diddly squat to* and try to build it:" is a bit complicated to try reproducing with.

**Comment by alistair23** [comment]
Ok, here are steps to reproduce it in a clean Fedora container.

```shell
sudo dnf install meson gcc g++ srecord python-pyyaml python-mako
git clone https://github.com/alistair23/opentitan.git -b alistair/meson-repro
cd opentitan
meson -Dot_version=opentitan-earlgrey_silver_release_v2-374-gf50ded219 -Dbin_dir=./build-bin -Dtock_local=false -Dkeep_includes=false -Dcoverage=false ./build-out
ninja -C build-out
```

It still requires cloning a giant repo, but no strange installs are required.

**Comment by jpakkane** [comment]
I tried that change and it seems to change the naming to the old one, This means that either:

- somewhere there is a code path that builds the path without calling that function
- the build definition files try to be sneaky and build an include path by hand (which of course fails)

The latter should be fairly easily checkable by grepping for something like `@exe` in the build files. Just grepping for `@` probably gives too many false positives because it is used in text substitutions.

**Comment by jpakkane** [comment]
The culprit is [this file in OpenTitan](https://github.com/lowRISC/opentitan/blob/master/util/meson-purge-includes.sh). It should preserve ephemeral directories but the regex only matches the old naming scheme, not the new one. Commenting out the Perl invocation from that line makes it work (but obviously the proper fix is to make the regex correct).

The file also says this:

> Meson does provide |implicit_include_directories|, support for this option is poor: empirically, Meson ignores this option for some targerts

This seems like a bug. If you can provide failing cases, please report them.

**Comment by alistair23** [comment]
Thanks! Changing the regex fixes the problem
