### ISSUE TITLE
gtkdoc: Error building gobject doc

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#3745]
Here is what `ninja -C _build gobject-doc` says:
```
gobject-scan.c:6:10: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
WARNING:root:Compiling scanner failed: 1, command: gcc -I./gobject -I../gobject -I./. -I../. -I./glib -I../glib -I./docs/reference/gobject/. -I../docs/reference/gobject/. -c -o gobject-scan.o gobject-scan.c
```

I don't think those include directories are right. `gobject-scan.c` is a generated file in `<builddir>/doc/reference/gobject` so I guess all `-I` args must be relative to that place, right?

**Comment by xclaesse** [comment]
@nirbheek I believe it's a regression introduced by 976c9abcd0348ffb29863ac2688c661eda524a47, but I was sure it was working not so long ago...

**Comment by xclaesse** [comment]
@Salamandar was already complaining about this in PR #2603, now I'm wondering why did it ever worked for me... weird.

**Comment by tp-m** [comment]
I've been seeing this for ages, not sure if it ever got fixed.

#3379 could be the same thing (with more info).

**Comment by xclaesse** [comment]
It is indeed dup.
