### ISSUE TITLE
macOS: LD version detection not working with Xcode 15.0 beta 3

### ISSUE THREAD

**Issue by osy** [mesonbuild/meson#11958]
The linker version detection happens here: https://github.com/mesonbuild/meson/blob/master/mesonbuild/linkers/detect.py#L197C6-L197C6

```python
        for line in newerr.split('\n'):
            if 'PROJECT:ld' in line:
                v = line.split('-')[1]
                break
```

However, the latest Xcode 15.0 beta 3 outputs this:

```
@(#)PROGRAM:ld  PROJECT:dyld-1009.5
BUILD 20:45:24 Jun 29 2023
configured to support archs: i386 x86_64 x86_64h armv6 armv7 armv7s armv7m armv7k arm64 arm64e arm64_32
LTO support using: LLVM version 15.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.0.12)
Library search paths:
Framework search paths:
ld: Undefined symbols:
  _main, referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Compare this with Xcode 14.3.1:

```
@(#)PROGRAM:ld  PROJECT:ld64-857.1
BUILD 23:13:29 May  7 2023
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
Library search paths:
Framework search paths:
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

As you can see, the project name changed from `PROJECT:ld` to `PROJECT:dyld` and the detection code no longer works.

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes the issue?
