### ISSUE TITLE
Statically linking with (pkg-config) dependency using `-lpthread` and `-lm`.

### ISSUE THREAD

**Issue by mgautierfr** [mesonbuild/meson#3879]
## Error

When compiling static executable, meson try to link with `/usr/lib64/libpthread.a` and `/usr/lib64/libm.a` directly.

## Context

My setup is a bit complex but I will try to simplify it (and I'm not sure my setup is relevant here)
Command output are real output.

I am statically linking my executable with a dependency (icu to name it) declaring `-lpthread -lm` in `Libs.private`.

My `meson.build` looks like something like that :
```
icu_dep = dependency('icu-i18n', static:true)
thread_dep = dependency('threads')
my_lib = static_library('mylib', [lib_sources.cpp],
                                   dependencies : [icu_dep, thread_dep])
my_exec = executable('my_exec', [exe_sources.cpp],
                                    link_with: my_lib,
                                    dependencies: [icu_dep, thread_dep])
```

When I compile my project, at link of `my_exec`, I have a "multiple definition of `pthread_attr_getstackaddr`" error :
```
ccache c++  -o test/parseUrl 'test/test@@parseUrl@exe/parseUrl.cpp.o' 'test/test@@parseUrl@exe/.._subprojects_gtest_googletest_src_gtest-all.cc.o' -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group src/libkiwix.a -pthread -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -licui18n /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libicuuc.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libicudata.a -lpthread -lm -pthread /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libzim.a /usr/lib64/liblzma.a -pthread /usr/lib64/libz.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libxapian.a /usr/lib64/librt.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libuuid.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libicui18n.a /usr/lib64/libpthread.a /usr/lib64/libm.a -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lrt /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libpugixml.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libaria2.a -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lctpp2 -Wl,--end-group -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -licui18n -lpthread -lm -pthread -pthread -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lrt -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lctpp2 '-Wl,-rpath,$ORIGIN'  
/usr/lib64/libpthread.a(libpthread.o): In function `pthread_attr_getstackaddr':
(.text+0x3410): multiple definition of `pthread_attr_getstackaddr'
/usr/lib64/libpthread.a(libpthread.o): In function `pthread_attr_setstackaddr':
(.text+0x3420): multiple definition of `pthread_attr_setstackaddr'
/usr/bin/ld: internal error ldlang.c 6543
collect2: error: ld returned 1 exit status
```

As we can see, meson try to directly link with `/usr/lib64/libpthread.a` and `/usr/lib64/libm.a`

There is 3 way of linking with pthread in this command : `-lpthread`, `-pthread` and `/usr/lib64/libpthread.a`

If I patch the icu .pc file, to change `-lpthread` to `-pthread`, I have no more duplicate definition but a lot of undefined reference to `_dl_x86_cpu_features`:

```
ccache c++  -o test/parseUrl 'test/test@@parseUrl@exe/parseUrl.cpp.o' 'test/test@@parseUrl@exe/.._subprojects_gtest_googletest_src_gtest-all.cc.o' -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group src/libkiwix.a -pthread -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -licui18n /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libicuuc.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libicudata.a -pthread -lm -pthread /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libzim.a /usr/lib64/liblzma.a -pthread /usr/lib64/libz.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libxapian.a /usr/lib64/librt.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libuuid.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libicui18n.a -pthread /usr/lib64/libm.a -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lrt /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libpugixml.a /home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64/libaria2.a -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lctpp2 -Wl,--end-group -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -licui18n -pthread -lm -pthread -pthread -pthread -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lrt -L/home/mgautier/Project/KIWIX/WORKING_DIR/BUILD_native_static/INSTALL/lib64 -lctpp2 '-Wl,-rpath,$ORIGIN'  
/usr/lib64/libm-2.26.a(e_atan2.o): In function `__ieee754_atan2_ifunc':
(.text+0x4062): undefined reference to `_dl_x86_cpu_features'
/usr/lib64/libm-2.26.a(e_asin.o): In function `__ieee754_acos_ifunc':
(.text+0x2262): undefined reference to `_dl_x86_cpu_features'
/usr/lib64/libm-2.26.a(e_asin.o): In function `__ieee754_asin_ifunc':
(.text+0x2282): undefined reference to `_dl_x86_cpu_features'
/usr/lib64/libm-2.26.a(e_exp.o): In function `__ieee754_exp_ifunc':
(.text+0x5d2): undefined reference to `_dl_x86_cpu_features'
/usr/lib64/libm-2.26.a(e_log.o): In function `__ieee754_log_ifunc':
(.text+0x15d2): undefined reference to `_dl_x86_cpu_features'
/usr/lib64/libm-2.26.a(e_pow.o):(.text+0x1352): more undefined references to `_dl_x86_cpu_features' follow
collect2: error: ld returned 1 exit status
```

The `/usr/lib64/libpthread.a` has been removed (and `-pthread` keep) but we still have `/usr/lib64/libm.a`.
From this issue (https://bugzilla.redhat.com/show_bug.cgi?id=1433347), it seems that we should never directly link to the libm.a but always use `-lm`

This is not working with meson 0.47.1.
I was previously working with meson 0.43.0 and it was ok. (I mainly stop upgrading meson because of https://github.com/mesonbuild/meson/issues/2785)
I can give you more information about my real use case if needed.

## Expected

I'm not sure about this but I think that meson should handle `-lpthread` and `-lm` (and other ?) as special case and should not try to find the `.a` to link directly with it.
Or maybe I'm doing something wrong on my side ...

**Comment by nirbheek** [comment]
This is a Meson bug. The obvious fix is that we should special-case `-lc` , `-lm` and `-lpthread` and never statically link to them. Are there any other 'special' glibc libraries that we shouldn't try to statically link to?

**Comment by ePirat** [comment]
Note that in case of cross compilation with mingw one might actually to want to statically link with winpthreads.
