### ISSUE TITLE
`meson install` broken with Windows MSI installer

### ISSUE THREAD

**Issue by dpirch** [mesonbuild/meson#3988]
After having installed meson via the MSI installer, I get this when trying to run `meson install` (or `ninja install`):
```
F:\projects\mesontest\libfoo\buildwin>meson install
Traceback (most recent call last):
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "meson.py", line 29, in <module>
  File "mesonbuild\mesonmain.py", line 379, in main
  File "mesonbuild\mesonmain.py", line 283, in run
  File "mesonbuild\minstall.py", line 23, in <module>
ImportError: cannot import name '__file__'
```
- the problem exists with `meson-0.47.1-32.msi`, also with `meson-0.47.0-32.msi`
- works correctly with `meson-0.46.1-32.msi`
- also works correctly when installing python and getting meson 0.47.1 via `pip3 install meson`
