### PR TITLE
linkers: fix regression when using lld after iOS changes

### PR DESCRIPTION
**Pull request by eli-schwartz**
```
$ LDFLAGS="-fuse-ld=lld" meson setup builddir/
[...]
    linker = lld_cls(
        compiler, for_machine, comp_class.LINKER_PREFIX, override, system=system, version=v)
TypeError: LLVMDynamicLinker.__init__() got an unexpected keyword argument 'system'
```

Fixes regression in commit cece1a7e9992a3bbcc35f90777ba22ba9d62b538. We pass system=system to the linker construction, which worked fine for Apple LLVM LD64 as that inherited `__init__` from DynamicLinker. But non-Apple LLD had an overridden `__init__` which wasn't adapted.

Even if it is thrown away and never used, since LLVM isn't an Apple linker, we still need to obey the argument contract.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
#14481

@bonzini looks like you introduced this while updating @freakboy3742's changes.

Also appears we don't actually test LLD on linux or this would be spotted...
